### ISSUE TITLE
(Enhancement) Hide Libraries / Notes

### ISSUE THREAD

**Issue by SimoneG97** [alialbaali/Noto#10]
Hi, first of all thanks for this app, I use it and I find it very useful.
I was wondering, is it possible to add the option to hide libraries / notes?
I ask about **hiding** because it should be a bit easier than _locking_ which has multiple security measures that should be taken.

**Comment by alialbaali** [comment]
I'm glad you liked that app!

I'm willing to go with locking because it would be a better feature, and it shouldn't be that hard to implement as far as I think.

I have come up with these 6 solutions for locking:
1. Locking libraries and notes
2. Locking libraries only
3. Locking notes only
4. Libraries vault (just like libraries archive)
5. Notes vault (just like notes archive)
6. Libraries and notes vaults

With the first three options, libraries or notes wouldn't be hidden, but their content would be, which is unlike the last three options where you wouldn't see anything (not even the count of the locked items) unless you open the vault.

My vote is on the last three options, particularly option 6. Let me know your thoughts.

**Comment by SimoneG97** [comment]
Cool!
So, for all the 6 solutions:
1. This option is usually the one that most app use (as far as I have seen), won't show people the note content, but they will know it's there
2. Will not give granular control over single notes
3. Will not give mass control over entire libraries

For 4-5-6 I think they share a similar "problem": you won't be able to keep their position as far as I can tell, since they will all
be placed in the respective vault (as in notes --> note vault || libraries --> libraries vault).
Every choice has its pros and cons, but using the vault system would kill 2 birds with 1 stone (hiding and locking),
so I think option 6 too would be the "best" choice here.

**Comment by alialbaali** [comment]
There are a couple of things we need to consider when implementing this feature:
1. Archiving notes and libraries
- Disable archiving notes and libraries when they're in the vault. This way, you won't be able to archive/unarchive items while they're in the vault, you'd have to unvault them first.
- Keep archiving notes and libraries. This way when unarchiving them, would also unlock them.
- Each vault has its own archive. IMO, this will make things more complicated.
2. Labels
- In the archive you don't have an option to filter by labels, however, you can add/remove labels to the note. Should the vault be the same?
- Or should the vault have an option to filter by labels?

What do you think?

**Comment by SimoneG97** [comment]
1. Probably much easier to disable archiving for vault notes. When trying to archive a note in vault, it should still "unvault then archive". Maybe with a disclaimer to inform the user, just to be sure (like "This note will be unlocked and then archived. Proceed? Y/N").
2. Not sure on this one. I would keep the vault functionality like the archive, be it with or without filter / label manipulation.

**Comment by alialbaali** [comment]
For the first option, what would you rather, solution 1 or 2 (with a disclaimer)?

**Comment by SimoneG97** [comment]
Confirm me if this is what you mean with option 1 and 2:
1. When trying to archive a locked note, it will be unlocked, then archived
2. When trying to archive a locked note, it will be archived (but still locked). When unarchiving, it will be unlocked.
If yes, I would say option 1 might be more intuitive for a simple user.

**Comment by alialbaali** [comment]
By option 1: You won't be able to archive notes unless you first unlock them(meaning archive option is not visible on locked notes).
By option 2: You will be able to archive notes (option is visible) but it will show you a disclaimer that this note is going to be unlocked in order to be archived.

**Comment by SimoneG97** [comment]
Oh my bad then, I misunderstood.
Option 2 seems more intuitive between the two (with a disclaimer of course).

**Comment by alialbaali** [comment]
Option 2 it is then. 
As for labels, I will make it look like an archive (meaning, you won't be able to filter by labels)

**Comment by alialbaali** [comment]
The implementation is almost finished, however, there's only two options on when the vault closes:

- Immediately,
- On app close

I'm thinking about adding more options like: 

- After 1 Hour
- After 4 Hours
- After 12 Hours

What do you think? Is that enough options, or should I add more? Maybe after 1 day too?

**Comment by SimoneG97** [comment]
I think with all of those options (with 1 day too) all kinds of use cases should be covered.
Nice touch on adding an option to choose between immediately or on app close!

**Comment by alialbaali** [comment]
The update is out now  (version `1.8.0`), feel free to check it and let me know your thoughts. I haven't added support for notes vault nor 1 day vault timeout option, because of two reasons:

1. I want to listen to users feedback and go from there.
2. I don't want to make the app so complicated.

If you have any suggestions about the implementation, let me know.

**Comment by SimoneG97** [comment]
Yeah, I tried breaking it by doing all I could think of.
No weird behaviour till now, so I guess it's all good for now.
Should I close this issue since the enhancement is now implemented or keep it open to wait for extra feedback?

**Comment by alialbaali** [comment]
I'm going to close it. People can create another issue if they have more feedback.
