### ISSUE TITLE
New Note Shortcut doesn't work when app icon is changed

### ISSUE THREAD

**Issue by AI-IMED** [alialbaali/Noto#100]
Steps to reproduce the problem:

- Create a new note shortcut 
- Change the app icon
- Click on the shortcut icon
- Result: "App isn't installed" message.

**Comment by uli-on** [comment]
Ah, you've found the trigger! I've had that, too.

**Comment by alialbaali** [comment]
This has already been fixed in 2.1.4. Please check it.

**Comment by afmbsr** [comment]
I'm using version 2.1.4 already, the problem is still.

**Comment by alialbaali** [comment]
Have you tried changing the icon?

**Comment by afmbsr** [comment]
The problem is resolved when removing the shortcut and creating a new shortcut, but when changing the application icon, the shortcut does not work again.

**Comment by AI-IMED** [comment]
Fixed it, Thanks
