### ISSUE TITLE
Weird labels sorting issue

### ISSUE THREAD

**Issue by uli-on** [alialbaali/Noto#102]
Currently (v2.1.4) I'm having two different sorting orders of my labels, depending on whether I view them in the notes themselves (wrong) or in the label sorting screen and in the notes list (both correct): Dragging labels has no influence on the order displayed in note view, which means I lost control of their order.

Where displayed in the wrong order, everything is sorted the way it was imported from a backup file some weeks ago, plus new labels appended to the end. 

The only major thing I did before (edit: today), that might have caused the issue, was deleting a folder with 10 notes in it.

This issue did not happen in v2.1.3, when I also deleted a folder with contents, so might have to do with the new "activated labels in front" feature.

Also I can't test whether that is replicable until labels can be moved again.

**Comment by alialbaali** [comment]
It's a known problem, see #95.

**Comment by uli-on** [comment]
Thanks for preponing the fix to the minor update, it repaired the wrong order. 

What's not as optimal as before prepending activated labels: the note must be closed and reopened in order to see/profit from the changed order.

**Comment by alialbaali** [comment]
Do you mean the order of selection or the order of the position?

**Comment by uli-on** [comment]
I'll try and give an example: Inside a note, I long tap a label, select Reorder and drag some labels to new positions. I then close the ordering pane and get back into the note, where the labels still have their previous (i.e. old) positions. I have to close the note and reopen it in order to find labels on their new positions.
