### ISSUE TITLE
Vault Help

### ISSUE THREAD

**Issue by JustNaturalCake** [alialbaali/Noto#106]
Im not sure how to move notes to the vault or how it works in general let me know if you can help.

**Comment by alialbaali** [comment]
You don't move notes to the vault, you move a folder to the vault. 

To move a folder to vault:
1. Open any folder except "General" folder.
2. Click on the three dots in the bottom bar.
3. Click "Add to vault".

Now the folder has been moved to the vault.

To access the folder in the vault:
1. Click on the hamburger menu in the bottom bar.
2. Click on the three dots at the top of the folders layout.
3. There is an option called "Folders vault", click on it.
4. Enter your current passcode, or set a new one.

**Comment by JustNaturalCake** [comment]
Ah okay works like like a charm

**Comment by alialbaali** [comment]
Glad to hear that!

If you need help with other things, let me know!
