### ISSUE TITLE
Checklist Feature

### ISSUE THREAD

**Issue by JustNaturalCake** [alialbaali/Noto#108]
![Screenshot_20220806-211114_Samsung Notes.jpg](https://user-images.githubusercontent.com/108516353/183263000-5606f072-4b79-47c2-9dd4-88fc25d97362.jpg)

A checkbox you can add infront of a sentence thats checkable simular to Samsung Notes, not sure how and where it could be possibly implemented but its a nice thing to have 😄

**Comment by alialbaali** [comment]
This feature is already proposed, please check #20 and #19.

**Comment by JustNaturalCake** [comment]
Ah alright feel free to close this
