### ISSUE TITLE
Split screen makes the app unresponsive

### ISSUE THREAD

**Issue by JustNaturalCake** [alialbaali/Noto#109]
Sometimes when go to the home menu and open notes again it starts stuttering and glitching, also seems like splitscreen mode is unsupported because then it becomes unresponsive even if i cover 80% of my screen

**Comment by JustNaturalCake** [comment]
Seems like my family got recorded too oops

**Comment by alialbaali** [comment]
This is probably related to #65. 



> Seems like my family got recorded too oops

You could remove the video if you want.

**Comment by alialbaali** [comment]
But in #65, it only happens when rotating the screen or changing the theme. Do you face it in some other way?

**Comment by JustNaturalCake** [comment]
I havent experienced it rotating, just only reopening the app once but splitscreen always starts glitching and becoming unresponsive

**Comment by JustNaturalCake** [comment]
I havent experienced it rotating, just only reopening the app once but splitscreen always starts glitching and becoming unresponsive

**Comment by JustNaturalCake** [comment]
Oh it definitely did start glitching when i rotated my screen when i rotated back to normal it still kept glitching

**Comment by alialbaali** [comment]
Yeah, all these problems have the same cause. I'm still working on a solution for it.

**Comment by uli-on** [comment]
In the 2.1.5 version it happens when leaving Noto with an opened note, and returning after a certain while (2h or so), no need to rotate.

**Comment by JustNaturalCake** [comment]
https://user-images.githubusercontent.com/108516353/183263494-ae3db6fd-a033-432b-a549-3fd1c3c03ff9.mp4

Yeah you need to rotate the screen and then it becomes immediately unresponsive nothing works and starts glitching only - way to fix is closing app by pressing home button and reopening the app (turned off mic background noises should be gone)

**Comment by alialbaali** [comment]
Yeah, definitely.

**Comment by JustNaturalCake** [comment]
It does seem like everything else in the app does work rotated perfectly, does look a bit weird and has some bugs but if i rotate before opening a note and the open a note while in rotation it doesnt glitch unless i rotate to normal and to side ways again

**Comment by alialbaali** [comment]
Yup, this bug made me tear my hair lol

**Comment by JustNaturalCake** [comment]
Oof

**Comment by alialbaali** [comment]
Thank you for using it!

I'm working hard on it, and I hope some day it will reach its full potential while remaining simple and minimal.

**Comment by alialbaali** [comment]
Did you download the app via Play Store or via GitHub?

**Comment by JustNaturalCake** [comment]
Play Store

**Comment by JustNaturalCake** [comment]
Its a fantastic app, im still a super beginner in Android development but ill start learning soon

**Comment by alialbaali** [comment]
I might have found a fix. I'm testing it right now as we speak.

**Comment by alialbaali** [comment]
> Its a fantastic app, im still a super beginner in Android development but ill start learning soon

If you need any help with learning, let me know. I could guide you and share some resources with you.

**Comment by JustNaturalCake** [comment]
Sounds great, looking forward for the next release, im not sure if i should reinstall from GitHub or continue with Playstore cause im not sure if play store even automatically updates or takea a while though

**Comment by alialbaali** [comment]
Play store is better since it automatically downloads updates after some time, unlike GitHub which you have to check releases regularly and download the new APK.

**Comment by JustNaturalCake** [comment]
I have seen some tutorials on YouTube ill try in a few days, ill try Kotlin ive seen some great apps using that language

**Comment by alialbaali** [comment]
Kotlin is such an amazing language. I LOVE IT. Would really recommend it to someone who is just starting.

**Comment by JustNaturalCake** [comment]
> Play store is better since it automatically downloads updates after some time, unlike GitHub which you have to check releases regularly and download the new APK.

I think I could activate notifications though and installing the new apk is super easy i just need to update not reinstall the whole app again

**Comment by alialbaali** [comment]
You can't go wrong with either of them. It's just a matter of preference. Noto will be available in F-Droid too sometime soon. It's currently available through Izzy Droid repo

**Comment by JustNaturalCake** [comment]
> Kotlin is such an amazing language. I LOVE IT. Would really recommend it to someone who is just starting.

Im on the right path then 😄

**Comment by JustNaturalCake** [comment]
> You can't go wrong with either of them. It's just a matter of preference. Noto will be available in F-Droid too sometime soon. It's currently available through Izzy Droid repo

I enjoy getting updates whenever Im able too so it should be GitHub I asume but ill do it later as I have some notes saved already on the Play Store app

**Comment by alialbaali** [comment]
You can export the content through the settings, since cloud backup is not yet available but in work.

**Comment by JustNaturalCake** [comment]
How long would it take on average to learn kotlin and publish my first app on my phone directly? (doesnt need to look the best just something that works) i have all the time im on vacation currently

**Comment by JustNaturalCake** [comment]
> You can export the content through the settings, since cloud backup is not yet available but in work.

ill test that and tell if it works

**Comment by alialbaali** [comment]
Well, to be honest with you, it depends on each person. But I'd say a month to get a grasp on the fundamentals, if you study for 2 hours a day.

**Comment by JustNaturalCake** [comment]
Oh yeah importing worked perfectly 👍

**Comment by alialbaali** [comment]
Nice

**Comment by JustNaturalCake** [comment]
> Well, to be honest with you, it depends on each person. But I'd say a month to get a grasp on the fundamentals, if you study for 2 hours a day.

Makes sense ill start researching kotlin and Android development in a couple days

**Comment by alialbaali** [comment]
I'd recommend Kotlin and Android Development documentations if you like reading. If you like online tutorials then these are great ones:

https://www.youtube.com/watch?v=F9UC9DY-vIU
https://www.youtube.com/watch?v=5flXf8nuq60

There's also Philipp which has quite amount of good tutorials: https://www.youtube.com/c/PhilippLackner/videos

**Comment by JustNaturalCake** [comment]
Are freecodecamp.org videos good too?

**Comment by JustNaturalCake** [comment]
I was planning on seeing those just waiting for next vacation house cause im ln mobile data rn

**Comment by alialbaali** [comment]
Ah, I see. No need to rush it, you can watch them when you can.

**Comment by JustNaturalCake** [comment]
ill take notes on the videos on Noto lol but yeah i got my school laptop with me im ready to start soon

**Comment by alialbaali** [comment]
Good to hear that!

**Comment by alialbaali** [comment]
Version 2.1.6 is released and this should be fixed. I'll let you know when it's available on the Play Store.

**Comment by alialbaali** [comment]
It's published on Play Store now. Check it and let me know.

**Comment by JustNaturalCake** [comment]
I haven't gotten an update yet, should ve available in a day probably, also if i dont reply its cause im on a mountain which the  4G signal is 50/50 its really bad

**Comment by alialbaali** [comment]
No problem at all. Have fun!

**Comment by JustNaturalCake** [comment]
Thank you, will 2.1.6 be available on GitHub soon?

**Comment by alialbaali** [comment]
It's already available.

**Comment by JustNaturalCake** [comment]
It seems like whenever the resolution changes or the view inside notes the app doesnt understand or can perform changes to it starts glitching cause when i use splitscreen everywhere else it works perfectly even if i use splitscreen and open a note after

**Comment by alialbaali** [comment]
Yeah, there was a bug and I found it, so this should be fixed with 2.1.6

**Comment by JustNaturalCake** [comment]
> It's already available.

Ah i see i just downloaded it ill test it

**Comment by alialbaali** [comment]
Okay

**Comment by JustNaturalCake** [comment]
It works perfectly now I can rotate screen, splitscreen everything not a single glitch 👌

**Comment by alialbaali** [comment]
Let's gooo 🚀

**Comment by Firsmall12** [comment]
> Sometimes when go to the home menu and open notes again it starts stuttering and glitching, also seems like splitscreen mode is unsupported because then it becomes unresponsive even if i cover 80% of my screen

What a slut. Fat

**Comment by alialbaali** [comment]
@Firsmall12 Excuse me, what?
