### ISSUE TITLE
"Go full screen during..." seems to make no difference

### ISSUE THREAD

**Issue by uli-on** [alialbaali/Noto#111]
What is this expected to do? Hide Android nav and status bar? Maybe also the folder name? I can't spot an effect. 
v2.1.6

**Comment by alialbaali** [comment]
It hides system bars (navigation bar and status bar).

**Comment by uli-on** [comment]
No effect here, sorry.

**Comment by alialbaali** [comment]
Can you provide me with a screenshot with the option being turned on?

**Comment by uli-on** [comment]
Yup! 
![Screenshot_20220829-222549](https://user-images.githubusercontent.com/35634829/187295062-c447d772-582d-468f-a41d-66fcd894052b.png)
Currently on 2.2.0 beta1

**Comment by uli-on** [comment]
Hm. The setting is about "full screen in reading mode", but after tapping the FAB there's still full screen in writing mode. This is neglectable yet confusing re "state I'm currently in".

**Comment by alialbaali** [comment]
It's only in Reading Mode to avoid any distractions while reading.

**Comment by uli-on** [comment]
Please read again (quoted from my previous post) :

> after tapping the FAB there's still full screen in writing mode

**Comment by alialbaali** [comment]
> Looks like this is fixed :)

I did nothing to fix it.





> Please read again (quoted from my previous post) :
> 
> > after tapping the FAB there's still full screen in writing mode

Can't reproduce.

**Comment by uli-on** [comment]
Currently this thread is about two topics. I opened it, cause the setting did not work for me, I never got a full screen reading mode. My "looks like it is fixed" refers to this first issue. The fix for that seemed to bring in another issue, though, namely that the full screen mode spanned even the editor view.

I can not reproduce this either, currently. I'll keep my eyes open, and report back,

Maybe this requires further preconditions like in the case I've been so stuck that I needed to ask for users' observations and then, after months, found steps how to reliably reproduce the issue. (Found it: #60)

**Comment by alialbaali** [comment]
Please, let me know if you're still facing this issue!

**Comment by uli-on** [comment]
Looks like it's fixed, but I'm not as versed in using Noto as I was

**Comment by alialbaali** [comment]
I see. Any problems you're facing?
