### ISSUE TITLE
Irrelevant to Noto just some issues im running into programming android apps, close if needed

### ISSUE THREAD

**Issue by JustNaturalCake** [alialbaali/Noto#113]
I don't know if your familair with android studio but i have some problems im having and i cannot find anywhere how to fix them

1. Gradle never stops syncing it has been hours and still syncing
2. Android project list also never loads ![20220807_212220.jpg](https://user-images.githubusercontent.com/108516353/183307805-b6a1a8bd-5e4e-4198-915d-06ba9e911428.jpg)
3. No modules show up when trying to add a configuration to run the programs

**Comment by alialbaali** [comment]
Can you post your build.gradle file?

**Comment by JustNaturalCake** [comment]
![image](https://user-images.githubusercontent.com/108516353/183308053-ba3ca0b4-64e2-4b83-847a-e5579a05a5a4.png)

Opening my project list with Project works fine but with Android it loops on loading

**Comment by alialbaali** [comment]
Are you connected to the Internet? Maybe, it's trying to download some stuff.

**Comment by JustNaturalCake** [comment]
Im on mobile data currently, i dont see why it needs 2+ hours to install but i wouldnt know im still new

**Comment by alialbaali** [comment]
Are you connected to a VPN?

**Comment by JustNaturalCake** [comment]
no, just normal 4G

**Comment by alialbaali** [comment]
Have you tried connecting to a local Wi-Fi network?

**Comment by JustNaturalCake** [comment]
theres no wifi networks around here, on a mountain for 5 days. although i'am connected to another phone's hotspot

**Comment by alialbaali** [comment]
I don't know what the problem could be, to be honest, but my guess is that it needs to download some stuff. 

I'd recommend trying again when you have access to a local Wi-Fi network. 

Sorry

**Comment by JustNaturalCake** [comment]
Could be downloading alot of files cause of first time use, my biggest problem currently is probably that i cant find a module in configuration editer, I have no way of running/debugging or exporting as an APK

**Comment by JustNaturalCake** [comment]
![image](https://user-images.githubusercontent.com/108516353/183308704-2e71dad9-a143-45b9-9ce6-187f5a5b89fd.png)

**Comment by alialbaali** [comment]
I think it needs to finish syncing first, then you'd be able to create a configuration. Could you try disconnecting from the network and sync again?

**Comment by JustNaturalCake** [comment]
It stopped syncing but im running into this now 
![image](https://user-images.githubusercontent.com/108516353/183308793-2f5b2b91-c503-45f3-adf4-111975f21313.png)
I tried resyncing but same error

**Comment by alialbaali** [comment]
Try this: File → Invalidate Caches → Invalidate and Restart

**Comment by JustNaturalCake** [comment]
ill try some other fixes but for now im still experiencing these bugs, might be fixed when im home installing it on my computer with ethernet but i dont know what to do currently

**Comment by alialbaali** [comment]
I'd say leave it until you're back home.

**Comment by JustNaturalCake** [comment]
ill watch those tutorials you mentioned but yeah ill do it at home

**Comment by alialbaali** [comment]
Okay then
