### ISSUE TITLE
[Proposal] URIs and numbers linked only in preview

### ISSUE THREAD

**Issue by uli-on** [alialbaali/Noto#114]
My motivation here is that currently these strings can not be edited in Noto after the note is reopened. On trying to set the cursor inside those elements, the "open with" panel pops up and the keyboard vanishes. Even workarounds don't work, namely cutting and re-pasting elsewhere, even into a new note: both yields a linked/non-editable URI.

**Comment by alialbaali** [comment]
Yeah, this is going to be the default behavior in 2.2.0, just how it's used to be before. Making links clickable in the editor caused this issue #101. And it's already been fixed by disabling links in the editor.

**Comment by uli-on** [comment]
> And it's already been fixed by disabling links in the editor.

Great, thanks!
