### ISSUE TITLE
Add an option to delete the vault passcode

### ISSUE THREAD

**Issue by AI-IMED** [alialbaali/Noto#116]
I was surprised after I created a passcode for the vault to try the feature, that there is no option to delete the passcode, it is enabled at least when the vault is empty, things would have been worse if I did not have a backup of the data before creating the passcode, because in this case I will have to  To accept one of the two options, either a clean install of the app and lose everything to get rid of the passcode, or succumb and save the passcode in my pocket :)

**Comment by alialbaali** [comment]
Really good suggestion. There could be an option to disable the vault, and move the folders out of the vault.
