### ISSUE TITLE
TickerView suffers from inversion and disintegration of Arabic text in the archive window

### ISSUE THREAD

**Issue by AI-IMED** [alialbaali/Noto#121]
TickerView animation is not disabled in the archive window when the language is Arabic, in v2.2.0-Beta1
Excuse Ali, what about: https://github.com/alialbaali/Noto/issues/50#issuecomment-1193678346

**Comment by alialbaali** [comment]
TickerView animation is fixed now. 

About #50, it should already detect if the device language (not the app) is Arabic.

**Comment by AI-IMED** [comment]
> About #50, it should already detect if the device language (not the app) is Arabic

I didn't see it in v2.2.0-Beta1

**Comment by AI-IMED** [comment]
#121
Fixed it, Thanks

https://github.com/alialbaali/Noto/issues/50#issuecomment-1193678346  
Fixed it, But
On the other hand, this resulted in a loss of tilting for creation/access date text, and animations in TickerView for  the other languages ​​when manually selected.

**Comment by alialbaali** [comment]
> On the other hand, this resulted in a loss of tilting for creation/access date text, and animations in TickerView for the other languages ​​when manually selected.

When changing app language or device language?

**Comment by AI-IMED** [comment]
App language

**Comment by alialbaali** [comment]
Other languages work fine for me. Could you please share a screen record?

**Comment by AI-IMED** [comment]
Sure

https://user-images.githubusercontent.com/38974362/189896957-665b3623-e92d-4b1b-aa51-e7479f1d0bab.mp4

**Comment by alialbaali** [comment]
The current implementation depends on the language device and not the app device, like you suggested in https://github.com/alialbaali/Noto/issues/50#issuecomment-1193678346. 

How do you think the implementation or the condition should be valued, then?

**Comment by AI-IMED** [comment]
Condition: When the device language is Arabic only.

**Comment by alialbaali** [comment]
Isn't that already the case?

**Comment by AI-IMED** [comment]
No, this is not the case, I do not want to lose the tilt of the text and animation in the TickerView when I choose the language of the application English

**Comment by alialbaali** [comment]
If the device language is set to Arabic, this would override any app language. As I am checking for the device language only. 

I think one condition might work, is that if I check if app language is Arabic or Follow System, and device language is Arabic too. That might resolve this issue.

**Comment by AI-IMED** [comment]
> I think one condition might work, is that if I check if app language is Arabic or Follow System, and device language is Arabic too. That might resolve this issue

Great!, problem solved, Thanks.
