### ISSUE TITLE
Add sorting and sequential selection to notes merge

### ISSUE THREAD

**Issue by AI-IMED** [alialbaali/Noto#122]
Thank you very much for adding the notes merging feature, and the feature would be even more awesome if sorting and sequential selection were added to it.

https://user-images.githubusercontent.com/38974362/187030439-92607ffb-c068-4e8f-a0fb-f4a128c173f8.mp4

**Comment by alialbaali** [comment]
This is already on my mind. I think the best way to implement it is to make it sequential, rather than providing custom sorting. What do you think?

**Comment by AI-IMED** [comment]
I agree with you, the best way to implement it is to make it sequential.

**Comment by AI-IMED** [comment]
Thank you for adding this improvement, But #135
