### ISSUE TITLE
Paging Support in Reading Mode

### ISSUE THREAD

**Issue by alialbaali** [alialbaali/Noto#123]
This feature would allow you paging/scrolling through notes while in reading mode, like a book reader.

**Comment by AI-IMED** [comment]
I hope the text brightness is reduced in reading mode, for the comfort of the eyes

![Screenshot_٢٠٢٢٠٨٢٨_١٠١٨٣١](https://user-images.githubusercontent.com/38974362/187064728-c5fa9d5b-182d-433a-b17c-88e01d48ea3d.png)

**Comment by alialbaali** [comment]
Good suggestion. I'm gonna add a settings option for that. Can you please create a separate issue for this? Thanks.

**Comment by AI-IMED** [comment]
okay.
