### ISSUE TITLE
The selection is returned, after removing it and opening a note

### ISSUE THREAD

**Issue by AI-IMED** [alialbaali/Noto#125]
https://user-images.githubusercontent.com/38974362/187434812-f6cb97ac-9709-4192-99d1-07df921d1bdc.mp4

**Comment by uli-on** [comment]
I can confirm that. Remarkable is that only these selections remain, that are triggered by the select option in the drawer, be it the initial selection or the subsequent possible "Select all".

**Comment by uli-on** [comment]
And like the "trapped in search" issue, recently, you can only get rid of the selection by opening a different folder and then returning.

**Comment by AI-IMED** [comment]
Not completely fixed, selection is re-enabled when following steps are performed:
- select all
- unselect all
- open folder edit option

**Comment by uli-on** [comment]
I can confirm that. You also find the previous selection is back again after returning from the app preferences.

**Comment by AI-IMED** [comment]
Fixed it, Thanks.
