### ISSUE TITLE
Two note options, not fully functional

### ISSUE THREAD

**Issue by AI-IMED** [alialbaali/Noto#129]
![Screenshot_٢٠٢٢٠٩٠٦_١١٣٣٥٨](https://user-images.githubusercontent.com/38974362/188589233-7b01a568-3236-416b-8ba5-69d2fc78bdb2.png)

**Comment by alialbaali** [comment]
What's the problem there? Because they're working fine for me, on both debug and release versions.

**Comment by AI-IMED** [comment]
I was on Beta1 when using the two options, I did not find that the note was moved/copied to the required folder, but now the problem disappeared even after I went back to Beta1 to confirm the problem! I don't know where it disappeared :), anyway I'll close the issue.
