### ISSUE TITLE
First selected label moves to the beginning in a new note.

### ISSUE THREAD

**Issue by uli-on** [alialbaali/Noto#134]
You seem to experiment with moving selected label(s?) to front. That's a great idea! However, currently it only works for the first label ever chosen in a note. Subsequently tapped ones do not move. Even on second/subsequent opening of the note.

**Comment by alialbaali** [comment]
Are you sure about that? I can't replicate it. When you select/deselect a label, it stays in the same place. And it is only moved when opening the note again.

**Comment by uli-on** [comment]
Yes, absolutely. To be clear, what I described happens inside a newly created note.

**Comment by alialbaali** [comment]
I managed to reproduce it. However, the bug is the first label is moving to the beginning in a new note, when it shouldn't. Labels should always stay in the same place, and only moved after opening the note again.
