### ISSUE TITLE
Open label filtered notes in Reading Mode 

### ISSUE THREAD

**Issue by uli-on** [alialbaali/Noto#138]
Are the Prev/Next buttons fully implemented yet, and should they reflect the label filtered results one day? Would be great to have that, too, cause the sorting order *seems* already implemented (haven't tested intensely there, though).

v2.2.0 beta2

**Comment by alialbaali** [comment]
Could you please provide more info? What I can understand is that you're asking to only open filtered notes in Reading Mode, just like when selecting notes, rather than the whole folder. Is that it?

**Comment by uli-on** [comment]
Yes, exactly :)
