### ISSUE TITLE
Text editor scroll stuck when typing long paragraph

### ISSUE THREAD

**Issue by napuzu** [alialbaali/Noto#14]
Noto Version : 1.6.0
Device : Samsung A30s
OS : android 11

When typing long paragraph for the first time, the scroll view is stuck in 1:1 square, does not extend following the length of the entire text.

https://user-images.githubusercontent.com/88090558/138592768-f99f273e-7a01-46e4-89da-b87b28a88b61.mp4

**Comment by alialbaali** [comment]
I'm closing this issue as this bug has been fixed in `1.6.1`.
