### ISSUE TITLE
Smoothing out "Undo"

### ISSUE THREAD

**Issue by uli-on** [alialbaali/Noto#141]
I am very grateful for having the possibility of using an undo feature in Noto and jump back and forth between versions. Nevertheless there are some edges about that feature set that might benefit from smoothing out. IMHO these are:

- [x] Reduce gap between buttons and keyboard and also flatten buttons a little, both eats up screen real estate important for writing and reading 

- [x] don't record any letter change, e. g. only completed words, i. e. save on blanks or punctuation, respectively* 
- [x] only show essential/changed areas in history. That way users can make their decisions easier because they can compare in history preview already. (The current situation is apt only for shorter notes*.) 
- [x] make different entries in history distinguishable by displaying dividers or - probably more evident - by using zebra striped backgrounds like currently only used between last version and "global rest". The current version might then have a border to set it apart from the rest. 
- [x] add a timestamp to each history entry (or numeratation) for easier orientation ("Am I seeing the most recent version or the oldest?")

*For opening this IMO medium sized text's history, edited in two Noto sessions (i.e. history steps halved), it certainly took far more than 10 sec, BTW, to stop scrolling (loading history) and let me choose,

**Comment by alialbaali** [comment]
>     * don't record any letter change, e. g. only completed words, i. e. save on blanks or punctuation, respectively*

Do you think this effect should be only for the history dialog, or the whole undo/redo functionality?

**Comment by uli-on** [comment]
If it is possible to separate the history from the undo steps, then it'd be probably quite useful keeping the capability of undoing single letters. My main criterion was, after a while of typing, the dialogue becoming really unwieldy with the current respecting every single change of a letter, and opening the dialogue then takes verrrry much time.

**Comment by alialbaali** [comment]
Done. 
Now, for the third point:

> only show essential/changed areas in history. That way users can make their decisions easier because they can compare in history preview already. (The current situation is apt only for shorter notes*.)

What do you think would be better, show only differences and remove similarities, or keep them both and highlight changes, like in the image?

![IMAGE 2023-02-07 23:57:35](https://user-images.githubusercontent.com/37933889/217447016-0b9c0e15-67d9-43d8-919b-4454de7ab85d.jpg)

**Comment by uli-on** [comment]
The screenshot version would offer more context, so choosing would be easier. I imagine I'd have a longer text and jump through the text editing here and there and would only be presented single words. Nope.

But - cause you're leaving that point open - it needs to be excerpted! (Your screenie might be meant as representing the whole text.)

**Comment by alialbaali** [comment]
I'm sorry, but could you elaborate more?

**Comment by alialbaali** [comment]
Version 2.2.1 has been released. I hope it resolved some of the issues you mentioned. Please let me know what more can be done. Thanks!

**Comment by uli-on** [comment]
I'd gladly test these changes if the crashes (#170) let me do so.

**Comment by uli-on** [comment]
This is now very usable, I've written a comparable portion of text as for the first post here and the history dialogue was open before I could lift my finger from the display :) Great!

The only thing that doesn't seem to be working properly is the coloured span that's indicating the last alterations, especially when not writing linearly from top to bottom but skipping back some paragraphs and amending words. There it happened that nothing was coloured at all. But still very helpful, that history view.

**Comment by alialbaali** [comment]
I believe the latest beta resolve all the issues regarding the first comment or tasks. For the colored span not working, please create another issue. 

Thank you!

**Comment by uli-on** [comment]
I'll close this, cause in my opinion these helper tools are now very useful and matured. Currently, I have no ideas what might be causing the loss of the coloured span when jumping back/upward in the text while editing, other than just this. Will keep my eyes open.
