### ISSUE TITLE
Add store page text to Crowdin

### ISSUE THREAD

**Issue by sakci** [alialbaali/Noto#142]
I think the Play Store content should be localized as well.

Examples from other projects:
- https://crowdin.com/project/loop-habit-tracker/ar
- https://weblate.bubu1.eu/browse/currencies/fastlane-f-droid/tr/

**Comment by uli-on** [comment]
And if so, please divide into minimal units, so not the whole chunk needs to be translated for any change on a single word.

**Comment by alialbaali** [comment]
I don't mind it to be honest, but wouldn't it be too much on translators? App content (strings.xml) is already large enough.

**Comment by uli-on** [comment]
Crowdin's integrated services supply readable translations already. I think we mostly smoothen out edges and replace here and there for more familiar phrases.

**Comment by sakci** [comment]
> I don't mind it to be honest, but wouldn't it be too much on translators? App content (strings.xml) is already large enough.

Industry standard is translating 2000 words a day (source: am professional translator).

So, no. It's not too much.

**Comment by alialbaali** [comment]
I have set up an integration with Google Play using Crowdin. However, the resulting strings aren't separated correctly. You can check it yourself in Crowdin.

<img width="554" alt="Screen Shot 2022-10-01 at 5 56 14 PM" src="https://user-images.githubusercontent.com/37933889/193415514-970e4d3e-586e-4a6c-9c94-edd0133e4fba.png">

**Comment by uli-on** [comment]
You might want to notify those translators not participating in this conversation about the current issue, so they don't start right off.

**Comment by alialbaali** [comment]
Too late, some translators are already working on them. However, I have set the file title to "DO NOT TRANSLATE YET".

**Comment by sakci** [comment]
> What's the solution here?

Using a Multilingual Excel template. I have worked on many localization projects by now and that's what they have used 95% of the time.

Details: https://store.crowdin.com/xlsx-excel

**Comment by alialbaali** [comment]
Is there a template I can use? Also is there any difference between using Excel and a CSV file in Crowdin?

**Comment by sakci** [comment]
> Is there a template I can use?

The one on the link above is simple enough, no?

<html><body>


String ID | Source text | French | German | Italian | Context | Max.length | Labels
-- | -- | -- | -- | -- | -- | -- | --
1 | String for translation 1 | Chaîne pour la traduction 1 | Zeichenfolge für die übersetzung 1 | Stringa per la traduzione 1 | Context for string 1 | 40 | mobile_app
2 | String for translation 2 | Chaîne pour la traduction 2 | Zeichenfolge für die übersetzung 2 | Stringa per la traduzione 2 | Context for string 2 | 40 | website
3 | String for translation 3 | Chaîne pour la traduction 3 | Zeichenfolge für die übersetzung 3 | Stringa per la traduzione 3 | Context for string 3 | 40 | emails


</body>
</html>

Something like this one should work (you don't have to use things like char. limit or labels if you don't need them). 

>Also is there any difference between using Excel and a CSV file in Crowdin?

You can use both XLSX and CSV files.

Even more details: https://support.crowdin.com/csv-xlsx-configuration/

**Comment by alialbaali** [comment]
I don't see an option to import or download the template:

<img width="1440" alt="Screen Shot 2022-10-02 at 11 28 50 PM" src="https://user-images.githubusercontent.com/37933889/193474918-6b3c5e12-c362-4ed6-b814-972fe0865008.png">

**Comment by sakci** [comment]
Ah, you meant a downloadable template file.

There isn't one that I am aware of. What I meant one was you creating your own template based on those examples.

I don't think there can be a one-size-fits-all template anyway, since there are too many variables (what languages will you include, will you include things like max length or labels etc.), so you have to create one your own.

**Comment by alialbaali** [comment]
I see.

**Comment by sakci** [comment]
Found another link about custom segmentation: https://blog.crowdin.com/2021/01/19/intuitive-way-to-add-custom-segmentation-for-text-based-formats/

Maybe it will work and you won't have to bother with creating a multilingual XLSX.

**Comment by alialbaali** [comment]
I have added the content as a CSV file. Let me know if there's anything else I should do.
