### ISSUE TITLE
Better indicate the destination folder when selecting one

### ISSUE THREAD

**Issue by uli-on** [alialbaali/Noto#145]
After moving a note from an archive to a different folder than the archive's one, that note doesn't arrive in that folder and also can't be found by a search. It remains member of an exported file, though.

v2.2.0-beta3

**Comment by AI-IMED** [comment]
Archived notes are copied/moved to the archive of the different folder

**Comment by uli-on** [comment]
Oooh, valuable hint! Thanks, Ahmed! That makes me think the target selection dialogue needs an improved/separate title, something like "Select target archive". And required one more request/GH-issue: "Include archives in search".

**Comment by alialbaali** [comment]
Can't reproudce.

**Comment by uli-on** [comment]
Yeah, sure, cause it's been a misunderstanding how moving archived notes works. Yet there's room for improvement, see my comment immediately before yours.
