### ISSUE TITLE
Suggestion: Make the back button/gesture close the app

### ISSUE THREAD

**Issue by Turbolqk** [alialbaali/Noto#150]
Right now pressing the back button/gesture opens the folder list and if you press it again then the app closes. It feels very unintuitive.

**Comment by alialbaali** [comment]
Pressing the back button used to close the app. However, some people complained about "leaving the app quickly", see #36.

I think the best way to solve this, is to provide an option in settings.

**Comment by alialbaali** [comment]
Any suggestions for the settings name? @Turbolqk

**Comment by Turbolqk** [comment]
How about Quick exit? With description like "Close Noto with a single back action."

**Comment by alialbaali** [comment]
Great!

**Comment by alialbaali** [comment]
This small feature is now supported in version 2.2.1. Please, let me know your thoughts!
