### ISSUE TITLE
Sorting of umlauts, diacritical characters etc.

### ISSUE THREAD

**Issue by uli-on** [alialbaali/Noto#154]
Most countries will probably be very content with the current alphabetic sorting of titles. Some countries, however, have some extra characters like umlauts, diacritical characters, accents etc. 

Speaking for countries using the German language, we will not easily find titles starting with umlauts because Noto treats them as separate characters and sorts them to the end of the alphabet, whereas Swiss, Austria and Germany list umlauts immediately between their base characters (ä next to a, ö to o, ü to u, and ß to ss.) 

French has even some more diacritical letters and seems to have separate sorting rules for French and Canadian French, but also close to their base characters, not after the z. And there will for sure be even more countries and languages.

That should be doable by a database change and the use of the system language's two-letter code or a pref in Noto's settings, but would make some people happier, certainly.

**Comment by alialbaali** [comment]
In which area specifically? Do you mean sorting/grouping across notes & folders?

**Comment by uli-on** [comment]
Originally, I was annoyed by not finding titles. But actually everything that can be sorted and/or grouped alphabetically would profit from such improvements in their area, notes, folders, labels, ... (did I leave out anything?)

**Comment by alialbaali** [comment]
Nope. Will be taken care of in the next release, #190.

**Comment by uli-on** [comment]
Ah, already implemented, thanks!
