### ISSUE TITLE
The app crashes when trying to share a text with it

### ISSUE THREAD

**Issue by AI-IMED** [alialbaali/Noto#156]
Attempting to share a text with the application causes the application to close immediately when clicking on the desired save folder.

**Comment by uli-on** [comment]
In case this is a real crash and not a refusal of any kind, Scoop can't catch it. But for whatever reason Scoop doesn't even catch all real crashes.

I can at least confirm that Scoop doesn't have Noto listed. And that the shared text never arrives in Noto, too. Which never feels like a crash here. 

Noto v2.2.0-RC

**Comment by alialbaali** [comment]
This has been fixed. No need for the stacktrace.
