### ISSUE TITLE
 When copying and pasting links, it adds the number 1 to the end of the link.

### ISSUE THREAD

**Issue by karswegas36** [alialbaali/Noto#158]
Link kopyala yapıştır yaparken linkin sonuna 1 sayısını ekliyor .

**Comment by uli-on** [comment]
Translated via deepl:
When copying and pasting links, it adds the number 1 to the end of the link.

**Comment by alialbaali** [comment]
Can't reproduce. Could you please provide me with the link you're copying? @karswegas36
