### ISSUE TITLE
Style inconsistency in filtering dialogues

### ISSUE THREAD

**Issue by uli-on** [alialbaali/Noto#160]
While the currently active choice in the mode selector of the label filter is highlighted using black colour (light theme), in the dialogues nested here it is the lightened colour of the respective folder. This situation does not contribute to intuitive operation.

I'd prefer the folder dependent colouring for creating consistency and only use black/white indicators for the high contrasting white/black folder accent colours. This would also have the advantage of emphasising the "Apply" button and thus making it better visible as the necessary final action.

**Comment by alialbaali** [comment]
Do you think the "Apply" button is redundant? I'm thinking of removing it from the layout.

**Comment by alialbaali** [comment]
What do you think?

![IMAGE 2023-01-15 23:37:45](https://user-images.githubusercontent.com/37933889/212599701-04c7416d-1681-4475-aef4-6563bc67d832.jpg)
![IMAGE 2023-01-15 23:37:50](https://user-images.githubusercontent.com/37933889/212599708-90808db5-428b-4938-ae2e-f2de85fbc964.jpg)

**Comment by alialbaali** [comment]
This should be fixed in 2.2.1. Let me know your thoughts!

**Comment by uli-on** [comment]
That's easier to grasp, and at one glance. One point, though: the colour contrast between the background and the chosen item indicator demands for a shadowy environment. Might be higher.

**Comment by alialbaali** [comment]
I see your point. Right now it's the same across the whole app. Might make it a bit darker in the future.
