### ISSUE TITLE
Reminders notification not showing on android 13

### ISSUE THREAD

**Issue by GitGitro** [alialbaali/Noto#162]
Probably it's because is missing the permission `<uses-permission android:name="android.permission.POST_NOTIFICATIONS" />`

**Comment by Frobby01** [comment]
Same problem here. Pixel 6 with Android 13.
![Screenshot_20230227-023644](https://user-images.githubusercontent.com/65205907/221452642-3f068957-be13-40d0-9845-44356bf60aa7.png)
As you can see, I don't even have the chance to enabled them or not.

**Comment by alialbaali** [comment]
This has been fixed in 2.2.1. I'm just waiting for translations to be done, so I can publish it. Sorry for the delay!

**Comment by alialbaali** [comment]
Version 2.2.1 has been released, please update me whether you're still facing this issue or not. Thanks.

**Comment by alialbaali** [comment]
You're welcome!
