### ISSUE TITLE
Import .json took forever 

### ISSUE THREAD

**Issue by idhirandar** [alialbaali/Noto#163]
Using google play store latest version and trying to import .json (exported from simplenote) took forever

**Comment by alialbaali** [comment]
Importing/Exporting only supports Noto data, and not any other app.

**Comment by idhirandar** [comment]
Which type of import file noto use ?

**Comment by alialbaali** [comment]
Noto uses JSON file type. The file structure is different for each app.

**Comment by idhirandar** [comment]
Ok
