### ISSUE TITLE
Problems with word count

### ISSUE THREAD

**Issue by Iseulj13** [alialbaali/Noto#166]
Hello, I've been using the app, and idk what I clicked on, but the app suddenly stopped showing the word count, I have looked everywhere, but I can't seem to figure out how to get it back.

I hope you can help ☺️

**Comment by alialbaali** [comment]
Hello, is it just the word count or is there something else that stopped showing?

**Comment by Iseulj13** [comment]
I'm pretty sure it's only the word count that stopped showing

**Comment by alialbaali** [comment]
Do you have a screenshot?

**Comment by Iseulj13** [comment]
Yes, here it is

**Comment by alialbaali** [comment]
I'm sorry, but I can't see any screenshots in your reply.
