### ISSUE TITLE
When pressing a backspace in the 1. Line the app crashes

### ISSUE THREAD

**Issue by HTaamas** [alialbaali/Noto#169]

**Comment by HTaamas** [comment]
Or just randomly

**Comment by HTaamas** [comment]
Uploading Screen_Recording_20230314-214244_Noto.mp4…

**Comment by alialbaali** [comment]
The screen recording isn't there, could you please upload it again? Thanks.

**Comment by Andy6697** [comment]
Having the same issue ever since the new update. I am on Android 13 on a Pixel 6a. Never had the issue prior to the update. Here is a screen recording:
https://user-images.githubusercontent.com/26486074/225200598-c1e43772-7383-431b-ace5-e8dbc4bdb5be.mp4

**Comment by HTaamas** [comment]
> The screen recording isn't there, could you please upload it again? Thanks.

Yes ofc

https://user-images.githubusercontent.com/96864185/225234155-5093557e-ab69-470c-88e5-7afd49e8e303.mp4

**Comment by HTaamas** [comment]
https://user-images.githubusercontent.com/96864185/225234834-43b5b78a-4cd1-47b0-b3fb-c3c09596b46b.mp4

**Comment by alialbaali** [comment]
This is related to #170. I'm working on a fix.

**Comment by alialbaali** [comment]
I just pushed an update with a potential fix for this problem. It's gonna take few hours before it's released on Play Store. However, if you have downloaded your app through GitHub/F-Droid, please update the app with the new APK from [here](https://github.com/alialbaali/Noto/releases/tag/v2.2.1).
