### ISSUE TITLE
Bugs in v2.2.1

### ISSUE THREAD

**Issue by AI-IMED** [alialbaali/Noto#171]
1. The app cannot be updated from Google play, I tried updating the application on more than one phone, and the result is the following message:
![٢٠٢٣٠٣١٥_١٣٤٥١٢](https://user-images.githubusercontent.com/38974362/225561450-ccaa3eae-67ed-4a04-abc0-ea9bb80ed0cb.jpg)

2.  **The Undo/Redo buttons are not activated for single word not followed by a space**.

3. The word counter is reversed when creating a quick note from Notification Center:
![٢٠٢٣٠٣١٥_١٣٤٤٤٥](https://user-images.githubusercontent.com/38974362/225562069-16461441-b02c-4dac-891e-65e67891e6f8.jpg)

**Comment by alialbaali** [comment]
Did you download the APK by any chance? I just updated, and I didn't face any issues.

**Comment by alialbaali** [comment]
Yes, since the APK isn't signed by Google, which prevents it from being overridden.

> Devices only accept updates when its signature matches the installed app’s signature. By letting Google manage your app signing key, it makes this process more secure.

More info can be found [here](https://support.google.com/googleplay/android-developer/answer/9842756?hl=en).

**Comment by alialbaali** [comment]
As for the second point, the undo/redo **history** buttons are grayed out as they're only being used to record word changes and not letters.

However, the regular undo/redo record letter and word changes. 

More info can be found here #141

**Comment by alialbaali** [comment]
Are you still encountering any issues here? @AI-IMED

**Comment by AI-IMED** [comment]
Problems solved here, Thanks
