### ISSUE TITLE
App crashes after trying to tap to write in next row

### ISSUE THREAD

**Issue by CookieLemur** [alialbaali/Noto#174]
As the title suggests, since upgrading to 2.2.1 on F-Droid, I'd go to a note written before the update, and everything functions as intended. (The note simply contains numbers 1-36, each written in the next row). However, after tapping to type on any other row (or other seemingly random places on the screen), the app instantly crashes. Nothing's lost or anything, just a inconvinence i know not the cause of.

**Comment by alialbaali** [comment]
Do you face this issue with 2.2.2?

**Comment by CookieLemur** [comment]
Just updated, the issue is resolved :)
Thanks for the blazing fast response, and I'll use the occasion to thank you for doing a great work on this app. It's my daily driver and I've been so happy with it!!

I'll mark the issue as resolved.
