### ISSUE TITLE
Cancel alarms when deleting/archiving notes

### ISSUE THREAD

**Issue by alialbaali** [alialbaali/Noto#186]
Currently, alarms stay active even after deleting or archiving a note. That shouldn't be the case at all. Alarms should be canceled as soon the note is archived or deleted.

**Comment by AI-IMED** [comment]
Regarding the deletion.. I think the correct behavior is to implement the Recycle Bin feature, cancel the deletion confirmation message, and change the warning message to "The note has been moved to the Recycle Bin."

**Comment by alialbaali** [comment]
I believe that's a different issue, which we have talked about in #74. This issue is regarding cancelling alarms, regardless of whether there's a Recycle Bin / Trash or not.

But, I do agree with you regarding that. The implementation actually isn't difficult or time-consuming. However, the design might overcomplicate the UI, and the app. My goal for Noto is to always keep it simple.
