### ISSUE TITLE
Communication Platform

### ISSUE THREAD

**Issue by alialbaali** [alialbaali/Noto#191]
This is an issue for providing Noto users with a messaging platform to share the latest news, plans, ideas, and progress, discuss issues, receive feedback, interact with the community, and provide support to each other. 

Now, I've talked about this with @napuzu, @uli-on, and now @AI-IMED mentioned it in #181. Please let me know your thoughts, and which platform do you prefer, and why. 

Suggested platforms:

- Discord
- Telegram
- Slack
- Session?
- Signal?
- Threema
- Other? Please list below!

Thank you!

**Comment by pgrilo** [comment]
My vote goes to Telegram. 
I see more user engagement on software projects on this platform than on a few others like reddit.

**Comment by AI-IMED** [comment]
+1 Telegram is the most popular among people.

**Comment by uli-on** [comment]
Although I'd prefer Telegram among the channels mentioned so far, I'd see Telegram & Co rather like a channel for reading about new features and updates, maybe also for quickly posting a stack trace. 

For asking questions or revealing details on my personal setup / background / situation /device or even for transmitting log files I'd always prefer email contact. 

Also, whenever I had an opportunity to have a look into an app's Telegram group I was glad when I closed their thread behind me because of the noise and jumble and lack of focus.

**Comment by uli-on** [comment]
Here's an example topic, BTW ([Amaze file manager](https://t.me/AmazeFileManager))

**Comment by alialbaali** [comment]
@uli-on I will probably restrict issues/feature request to GitHub exclusively, that way it would be more organized & easier to maintain. The group would only be up for discussions/help/share among the community. 

I checked the example you gave, and I don't picture Noto group/channel to be like that. If I had to, I would probably separate/categorize them, where releases/changes/announcements are in one thread or channel, and the real human communication would be in a different channel/group. 

That way it wouldn't be chaos, and it would be simple for everyone. 

Let me know what you think.

**Comment by alialbaali** [comment]
I'm debating between Slack & Telegram. I believe Slack is more professorial, and has more integrations with the Software Development. However, I've seen apps use Telegram. So, can you guys help me decide? Maybe highlight features, or functionalities I'm missing?

**Comment by x-0D** [comment]
+1 Telegram

**Comment by alialbaali** [comment]
Please join the Telegram group using [this](https://t.me/notoapp) link. Thank you!

**Comment by alialbaali** [comment]
![IMAGE 2023-07-20 22:23:22](https://github.com/alialbaali/Noto/assets/37933889/1d1a9a81-0cfc-45d5-91fe-66fd893d48b0)

Would you support a **temporary** banner for the Telegram community? Or do you think it looks like an Ad?

**Comment by x-0D** [comment]
@alialbaali looks styled and comfortable
