### ISSUE TITLE
Russian Support

### ISSUE THREAD

**Issue by x-0D** [alialbaali/Noto#192]
Russian completed but still not in app. Why?

**Comment by alialbaali** [comment]
It'll be in the app in the next release 2.3.0, if it is completed.

**Comment by alialbaali** [comment]
Russian language is included in version 2.3.0-Beta1. Let me know if there's anything I can do!

**Comment by x-0D** [comment]
Thank you very much for adding Russian language support in 2.3.0-b1. is there anything we can do with 
"planned" button? In Russian, maybe, we need to replace "Запланировано" with "В планах" to keep more short but synonym werb.
![Screenshot_2023-06-02-23-58-12-531_com noto](https://github.com/alialbaali/Noto/assets/87000516/67717693-4e70-4e42-81fe-fbd6f3bfa9eb)

**Comment by alialbaali** [comment]
Thank you for your work bringing Russian support to Noto :)

You don't have to imitate the exact word. You can change the word however you want, as long as it has a similar meaning.

**Comment by alialbaali** [comment]
Also, did I mention you correctly in the app?

**Comment by x-0D** [comment]
Absolutely correct mentioned. I updated some strings on crowdin, maybe there's needed to include them to new build.

**Comment by alialbaali** [comment]
No worries. I'll include them in the next beta!
