### ISSUE TITLE
v2.3.0-beta1: Plus button disappears from notes list

### ISSUE THREAD

**Issue by uli-on** [alialbaali/Noto#193]
The plus button for creating notes vanishes from the notes list after archiving a note.
EDIT: it can't be brought back by any scrolling.

Android 10
Fairphone 3
Not rooted, no manipulations
Play Services 23.13.12
Webview 111.0.5563.116

**Comment by uli-on** [comment]
The issue is a different one as it can be triggered by selecting and opening & closing the options drawer, already.

**Comment by alialbaali** [comment]
This is fixed in 2.3.0-Beta2.

**Comment by uli-on** [comment]
Yup, that's no more, thanks!
