### ISSUE TITLE
v2.3.0-beta1: Select all while filtering

### ISSUE THREAD

**Issue by uli-on** [alialbaali/Noto#194]
Since 2.3.0-beta1 there's this nice Select-all FAB. It's not yet respecting the label filter, though: I have "59 notes, 5 filtered, 59 selected" after I pressed it.

**Comment by alialbaali** [comment]
This is fixed in 2.3.0-Beta2.

**Comment by uli-on** [comment]
Yup, that's fixed, too, thanks :)
