### ISSUE TITLE
Selection marks vanish after opening and closing the options' drawer 

### ISSUE THREAD

**Issue by uli-on** [alialbaali/Noto#196]
**Steps to reproduce**

1 Long tap a note until the check mark appears
2 Tap the FAB to open the options drawer
3 Close the drawer again (without any action) 
4 The checkmark is gone

v2.3.0-beta1
Android 10
Fairphone 3

**Comment by alialbaali** [comment]
This is definitely intentional. Since the user would probably perform an action, and the action could alter the selected notes, (e.g. moving notes).

However, I could keep the selection until the user actually performs an action, rather than disabling it when opening the dialog.

**Comment by alialbaali** [comment]
This should be fixed in 2.3.0-Beta2.

**Comment by uli-on** [comment]
Thanks!

**Comment by alialbaali** [comment]
You're welcome!

**Comment by uli-on** [comment]
I just discovered that assigning labels with the multi-selection tool does not remove the selection markers, so one can label a complicated selection "Archive" and then move it there without selecting the same notes a second time. Great, that's very effective.
