### ISSUE TITLE
Utilizing the Save to Noto shortcut crashes Noto

### ISSUE THREAD

**Issue by pgrilo** [alialbaali/Noto#203]
**ISSUE**

The *Save to Noto* shortcut consistently crashes Noto before a new note is created.

To reproduce:
- Open any other app
- Select some content
- Action -> Share -> Save to Noto

**LOG**

```
Caused by:
java.lang.IllegalArgumentException:
Required argument "title" is missing and does not have an android:defaultValue
 at y6.h0.fromBundle(SourceFile:116)
```

**SOLUTION**

Add `defaultValue`and `nullable` to the `selectFolderDialogFragment` argument.

`res/navigation/nav_graph.xml`
```
<dialog
    android:id="@+id/selectFolderDialogFragment"
    android:name="com.noto.app.main.SelectFolderDialogFragment"
    android:label="SelectFolderDialogFragment">
    
(...)
    
    <argument
        android:name="title"
        android:defaultValue="@null"
        app:nullable="true"
        app:argType="string" />
</dialog>
```

Thank you

**Comment by alialbaali** [comment]
This should be fixed in 2.3.0-Beta3.
