### ISSUE TITLE
Add to vault: Contradicting confirmation message 

### ISSUE THREAD

**Issue by uli-on** [alialbaali/Noto#207]
Open a folder and use the three-dot menu to access the folder options sheet. There is the button "Add to vault". When I tap on it a message comes up saying that the folder has been removed(!) from vault, and vice versa, depending on the initial situation.

Noto v2.3.0-beta2
Fairphone 3
Android 10 with GMS updated to v23.13.12

**Comment by alialbaali** [comment]
I don't seem to have this issue. You are talking about the bottom snackbar right?

**Comment by uli-on** [comment]
Yup, exactly, and I've checked that it's not only happening in German language (which could have been my own fault by mistaking strings during translation).

**Comment by uli-on** [comment]
Seems I've found a way worth replicating: Create 2 subfolders inside the top level parent, open the parent, use the three dot menu and add to vault. If not yet happening,  create at least one note in each of the subfolders.

**Comment by alialbaali** [comment]
Thank you! I have managed to reproduce it.

**Comment by alialbaali** [comment]
I also noticed the same bug happens when trying to archive the folder.

**Comment by uli-on** [comment]
This has been convinced to give in. Thanks!
