### ISSUE TITLE
bug while creating widget

### ISSUE THREAD

**Issue by skanull** [alialbaali/Noto#21]
the screen kind of blinks when creating note widget, so can't create the widget at all. it doesn't happen when creating the library widget but when i click the plus sign, it blinks again.

**Comment by alialbaali** [comment]
Could you please provide a video? There isn't much info about the issue.

**Comment by skanull** [comment]
yes sorry I don't know how else to describe it. but here is a [screen capture](https://imgur.com/a/amQBZfV) 

the first part is when I try to create a "note" widget and the second part is when I try to create a "library" widget. I just press the home button to exit this

**Comment by alialbaali** [comment]
Thanks for the info. Can you tell me whether the issue happens with the app when you launch it or is it just with widgets?

**Comment by skanull** [comment]
the issue only persists when creating widget, the app works great

**Comment by skanull** [comment]
fixed in the new update thanks
