### ISSUE TITLE
Archive: Screen doesn't go off

### ISSUE THREAD

**Issue by uli-on** [alialbaali/Noto#211]
If the setting Leave Screen On In Reading Mode is chosen, the screen remains turned on forever while only in an archive.

**Comment by alialbaali** [comment]
The same happens with other Reading Mode features while viewing the archive.

**Comment by uli-on** [comment]
> The same happens with other Reading Mode features while viewing the archive.

I'm glad I could point to some things worth testing. I'm looking forward to the final version.

**Comment by uli-on** [comment]
One less room lamp. Thanks!

**Comment by alialbaali** [comment]
LOL. You're welcome!
