### ISSUE TITLE
Flickering after special language switch

### ISSUE THREAD

**Issue by uli-on** [alialbaali/Noto#213]
As one of the translators for Noto I'm probably much more often switching languages than most of the normal users, and I only found this by accident, but as this here is one of the less pleasant situations to encounter:

After returning from English to one's own language by selecting Follow System, Noto flickers wildly — same like we've had already one year ago, back then triggered by rotating the device — while it is constantly switching between English and German at quarter second intervals, rendering Noto unusable for the moment. This can only be stopped by swiping it out of the app switcher.

For replicating this, it is necessary to leave the settings after choosing a particular language. Only then return to the languages section and choose Follow System. 

Switching by selecting a language explicitly doesn't have this effect, only by choosing Follow System. 

You can see another, shorter flickering on every 2nd(! Yup!) switching to other languages, although less aggressive and only flickering 2-3 times.

**Comment by alialbaali** [comment]
I'm very familiar with this bug, and it's been happening for a while. However, I couldn't find a right way to fix it yet, which made me to ignore it for now, since there's a workaround.

**Comment by alialbaali** [comment]
Good news, a fix will be applied, and be in the next release!

**Comment by uli-on** [comment]
Yess, stable!!
