### ISSUE TITLE
Labels multiplied after transferring notes between folders

### ISSUE THREAD

**Issue by uli-on** [alialbaali/Noto#214]
I am actually describing two issues below, but there may be a connection between the two, and so it is best to describe the full process. 

To transfer notes from one top level folder to another nested in the first one, you currently have to move the notes to a third one first, since Noto does not handle moving directly from top folder to child folder at the moment. In doing so and/or when subsequently moving four notes to the actual destination folder (the child folder), the labels of the notes were multiplied in a special way. Example: all four notes had the label "A", the destination folder now has the label "A" four times. Three of the notes had the label "B". Now the destination folder has this label three times, etc. 

Accordingly, by filtering with one of the labels, only one note can be selected at a time.

One more detail, cause recently it was crucial for another issue with nested folders: the parent folder contained two child folders. The interim top level folder contained no folders but held two notes and has already been used for transferring notes  in earlier versions of Noto. Their labels have been deleted before.

**Comment by alialbaali** [comment]
> One more detail, cause recently it was crucial for another issue with nested folders: the parent folder contained two child folders. The interim top level folder contained no folders but held two notes and has already been used for transferring notes in earlier versions of Noto. Their labels have been deleted before.

Could you elaborate more on this please?

**Comment by uli-on** [comment]
The folder tree is set to "sort manually". The notes in the interim folder were created in June, when beta-1 was already released, so the interim folder was quite likely created with beta-1, too, for testing my idea of an archive in a nested folder. For any information else please ask more specifically.

**Comment by alialbaali** [comment]
So, the labels getting duplicated has been fixed, and will be released in the next version. However, I'm still missing what's going on in the last paragraph. Is there a bug you're reporting, or just a thought regarding an archive in a nested folder like #197?

**Comment by uli-on** [comment]
Ah, I see, it was the wording in the last sentence :) No, that's just to say that there weren't any remaining labels. Thanks for the fix 👑 That's great!

**Comment by uli-on** [comment]
✅ Fixed. Thank you 😊

**Comment by alialbaali** [comment]
You're welcome!
