### ISSUE TITLE
The app crashes when clicking anywhere on the widget

### ISSUE THREAD

**Issue by itsmohmans** [alialbaali/Noto#219]
**Device**: Samsung A53, Android 13, One UI 5
**To reproduce**: Add widget to homeacreen then click on anywhere on it.

This issue has appeared after `2.3.0-BETA3` or `2.3.0-BETA2` I'm not sure which one exactly, but I cleared the cache and installed the latest update `2.3.0-RC` and the issue is still there.

**Comment by alialbaali** [comment]
This has been fixed in 2.3.0.

**Comment by itsmohmans** [comment]
Great! Thanks for your work.
