### ISSUE TITLE
F-Droid badge

### ISSUE THREAD

**Issue by IzzySoft** [alialbaali/Noto#221]
I see you're using an F-Droid badge to point to your app in my repo. First, thanks for adding the link! But to avoid confusion, maybe you'd rather like to [pick a badge here](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) as a replacement fot the graphic, so it's clear where the link leads to? :smiley: Thanks a lot!

**Comment by alialbaali** [comment]
Oh, my bad! I didn't know there was a badge for your repo. I'll update the README accordingly. Thank you for letting me know! 🙂

**Comment by alialbaali** [comment]
The badge has been updated. Let me know if there's anything else!

**Comment by IzzySoft** [comment]
Looks fine, thanks! And I just had someone who was puzzled about that reporting to me, which is why I came looking :wink:
