### ISSUE TITLE
Automatically adjust screen position 

### ISSUE THREAD

**Issue by tsyqax** [alialbaali/Noto#226]
If there is no line on the screen to input text, **the screen position is adjusted** so that **the input line is at the top.**

However, if you type from the top or middle,
**the line will be moved to the top even if it is on the screen.**
(It didn't seem to work as above because it couldn't be scrolled further in the last position.)

If there is an input line on the screen, is there **a way to prevent it from automatically moving to the top?**
(Because the above content is obscured and **may be inconvenient**)

**Comment by pgrilo** [comment]
I also find this behavior inconvenient.
I Think that the automatic scrolling when the user starts typing should only happen if the cursor is obscured by the keyboard or if is out of view.

**Comment by alialbaali** [comment]
I'll try to work on a better way for handling this. Thank you!

**Comment by alialbaali** [comment]
@tsyqax Is everything good on your end?

**Comment by tsyqax** [comment]
Yes, It is good in my Noto.
Thanks!
