### ISSUE TITLE
Notes open scrolled down

### ISSUE THREAD

**Issue by uli-on** [alialbaali/Noto#227]
In v2.3.1, all notes long enough to be scrollable open scrolled to the bottom. The switch for "Remember scroll position" is set to off, BTW.

Didn't have an opportunity to check that in v2.3.0, but I'm quite sure that was not in the previous betas already.

**Comment by uli-on** [comment]
Thanks for the fix! 😀

**Comment by alialbaali** [comment]
You're very welcome!
