### ISSUE TITLE
[Q] Difference between Noto.apk and Noto-F-Droid.apk

### ISSUE THREAD

**Issue by rusty-snake** [alialbaali/Noto#229]
What is the difference between Noto.apk and Noto-F-Droid.apk

**Comment by alialbaali** [comment]
The Noto-F-Droid.apk is the APK used for publishing on F-Droid as it has a different build config which is required to publish on F-Droid. However, you can simply ignore it, and just use the Noto.apk. There's no difference in features or functionality.
