### ISSUE TITLE
Add Ability to Draw and Add images

### ISSUE THREAD

**Issue by testes-tester** [alialbaali/Noto#233]
I have some notes that need additional context, and sometimes context cannot be transferred through text only, and that's where images come in useful. Would be much appreciated if images can be imported in a note or maybe even on a folder to make a folder more easily recognizable. Drawing on a note would also be useful to add emphasis on some words, or just for aesthetics. The drawing feature could be like how people could draw on a notes in the Samsung Notes app.

**Comment by alialbaali** [comment]
Adding images to notes is planned. Please check #41 & #117 for any further updates.
