### ISSUE TITLE
Multi selecting for notes

### ISSUE THREAD

**Issue by ColdMeem** [alialbaali/Noto#25]
Hello , Dev and thanks for making this great app .
Can you add multi selecting for notes to do bulk operations like deleting , moving , ..... ?

**Comment by AI-IMED** [comment]
v2.2.0-Beta1:
Notes are automatically reselected when switching to landscape mode.

https://user-images.githubusercontent.com/38974362/187022275-2ea98da6-8ca9-47d6-ba6e-012346b70d9c.mp4
