### ISSUE TITLE
Undo and Redo

### ISSUE THREAD

**Issue by ColdMeem** [alialbaali/Noto#26]
Hello , Dev and thanks for making this great app.
Can you add undo and redo for notes ?
And it would be better if you make undo button accessible or visible only when a change is made to note and not from a start as note is opened , as when it become visible its like an alert or sign that a change has been made to note

**Comment by alialbaali** [comment]
Undo/Redo with history view is coming in the next update! 

You can use this [link](https://www.reddit.com/r/notoapp/comments/vfp1uz/undoredo_with_history_view_is_coming_in_the_next/) to check it.

Note: The actions will be clickable only when the keyboard is open. And, they will be disabled/enabled according to the text edits. New note always starts with disabled buttons.

One more thing, title and body have different undo/redo history, so doing undo/redo on one doesn't affect the other one.

**Comment by alialbaali** [comment]
Undo/Redo is out now with version 2.1.0. Please check it and let me know your thoughts.
