### ISSUE TITLE
Crashes trying to open any note

### ISSUE THREAD

**Issue by WTechNinja** [alialbaali/Noto#3]
Here's the stack trace, I can't open my notes at the moment, hopefully this is a quick fix. I really like the app.
My device is a Samsung Galaxy S8 SM-G950W running stock Android 9, and the app version is the latest 1.3.2 from f-droid.

`FATAL EXCEPTION: main Process: com.noto, PID: 21486 java.lang.IllegalArgumentException: Max number of dynamic shortcuts exceeded at android.os.Parcel.createException(Parcel.java:1970) at android.os.Parcel.readException(Parcel.java:1934) at android.os.Parcel.readException(Parcel.java:1884) at android.content.pm.IShortcutService$Stub$Proxy.addDynamicShortcuts(IShortcutService.java:595) at android.content.pm.ShortcutManager.addDynamicShortcuts(ShortcutManager.java:396) at com.noto.app.note.NoteFragment$setupState$1.q(:55) at com.noto.app.note.NoteFragment$setupState$1.n(:2) at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.a(Unknown Source:73) at kotlinx.coroutines.flow.StateFlowImpl.b(:14) at kotlinx.coroutines.flow.StateFlowImpl$collect$1.q(Unknown Source:12) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.r(:2) at v6.f0.run(Unknown Source:86) at v6.k0.U(:2) at v6.j.s(:3) at v6.j.B(Unknown Source:2) at kotlinx.coroutines.channels.AbstractChannel$b.i(Unknown Source:4) at x6.e.j(:2) at x6.b.t(Unknown Source:0) at kotlinx.coroutines.flow.internal.CombineKt$combineInternal$2$1$invokeSuspend$$inlined$collect$1.a(Unknown Source:69) at kotlinx.coroutines.flow.FlowKt__TransformKt$filterNotNull$$inlined$unsafeTransform$1$2.a(Unknown Source:56) at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.m(:1) at kotlinx.coroutines.flow.internal.SafeCollector.u(:9) at kotlinx.coroutines.flow.internal.SafeCollector.a(Unknown Source:0) at kotlinx.coroutines.flow.FlowKt__ChannelsKt.a(:9) at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.q(:1) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.r(:2) at v6.f0.run(Unknown Source:86) at android.os.Handler.handleCallback(Handler.java:873) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loop(Looper.java:214) at android.app.ActivityThread.main(ActivityThread.java:7050) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964) Caused by: android.os.RemoteException: Remote stack trace: at com.android.server.pm.ShortcutService.enforceMaxActivityShortcuts(ShortcutService.java:1702) at com.android.server.pm.ShortcutPackage.enforceShortcutCountsBeforeOperation(ShortcutPackage.java:1104) at com.android.server.pm.ShortcutService.addDynamicShortcuts(ShortcutService.java:1990) at android.content.pm.IShortcutService$Stub.onTransact(IShortcutService.java:119) at android.os.Binder.execTransact(Binder.java:739)`

**Comment by alialbaali** [comment]
Thank you for reporting the issue.

A fix should be available in the next release.

**Comment by alialbaali** [comment]
Please check the last version and let me know if the issue has been fixed.

**Comment by WTechNinja** [comment]
Sadly, I'm still getting the same crash. Anything I could do to get around it?

**Comment by alialbaali** [comment]
1.3.4 is released. Check it and let me know!

**Comment by WTechNinja** [comment]
Yes! It's fixed. Thank you so much

**Comment by WTechNinja** [comment]
Yes! It's fixed. Thank you so much
