### ISSUE TITLE
Crash, with failed exports /imports of text notes 

### ISSUE THREAD

**Issue by franco27** [alialbaali/Noto#31]
Version 1.8.0

Hello
1. I go to the settings, to export my data
2. the file manager opens and I authorize the creation of the file in the folder.
3. then after, your application closes immediately.
4. the file created has a size of 0 KB

I can't export my notes or data

**Comment by franco27** [comment]
I had Noto installed, downloading the APK from GitHub.  So I'm stuck doing a backup.
 It is very unfortunate that I cannot send my data to Google Drive.

 I just finished sharing (or forwarding) all my notes to another app.

 1 .  I uninstalled Noto.  And I reinstalled Noto from the Google PlayStore.

 2. I had created a backup last December of my data.
 Noto closes immediately when I try to restore or import my data file.  The immediate closing of the application (or crash of the application) occurs after selecting the file.

 And still the same problem, to make a backup.  Noto closes after choosing the folder.

 So still stuck.  And no possibility to save or restore its data.
 I should point out that I did not have these problems before.  (With a previous version)

**Comment by franco27** [comment]
I just reinstalled version 1.7.1

 No problem to backup and restore.

 Then updated to version 1.7.2

 Also I can still perform backups and restores.  (Export and import data successfully).  version 1.8.0 failed

**Comment by alialbaali** [comment]
This has been fixed in the latest version (2.0.0), please check it and let me know!

**Comment by franco27** [comment]
I confirm that, it is solved with version 2.0.0
