### ISSUE TITLE
Exported files can not be re-imported

### ISSUE THREAD

**Issue by uli-on** [alialbaali/Noto#33]
Noto v2.0.1 seems to not recognise files exported by the 2 version, existing files are grayed out, even those that I suffixed with  .json,. zip, or even .txt

Noto v2.0.1 (from F-Droid) 
Android 6.0.1 (with GMS upd. to 21.18.16, cn=M sdk=23)
Webview 97.0.4692.87
Motorola Moto G4
device not rooted

**Comment by uli-on** [comment]
OK, I found a possible reason: One of 
- me
- Android file management
- Noto
named the backups such that they contained 
- no .json suffix
- parentheses
After naming the file correctly, I could import it.

Ali, apologies if both of these were caused by me (which I don't think so). I'm currently moving my data over to an Android 10 phone and will see one by one which of my bug reports still apply then.

**Comment by alialbaali** [comment]
The output file structure has changed in v2. It's now a single JSON file, instead of a Zip folder.

Let me know if you're still facing this issue or whether you found what causes it.

**Comment by uli-on** [comment]
For v2.0.1 I've already answered before you asked, see post#2. For the new
version I can't tell yet, the Izzy server times out.

**Comment by uli-on** [comment]
For completeness, exporting from a v2.1.1 and reimporting into the same version (even with the brackets in file names mentioned above) works, as expected.

**Comment by AI-IMED** [comment]
I get the same problem that @uli-on mentioned in his first comment, I tried the latest version and many previous versions on a phone running Android 9, the exported file does not end with the suffix (.json), even if I modified the name by adding the missing suffix to the end of the name, I tried importing  json file I transferred from my primary Android 12 phone and the app didn't recognize it either.

**Comment by AI-IMED** [comment]
Yes, the app started exporting data with suffix (.josn), but it still can't recognize it when I want to import it, because it's grayed out.

This issue is facing me on the phone running Android 9.

**Comment by AI-IMED** [comment]
Fixed it,Thanks.
