### ISSUE TITLE
Labels can take invisible state

### ISSUE THREAD

**Issue by uli-on** [alialbaali/Noto#34]
In the current 2.0 version some labels vanish from the notes list (take space without being displayed). This seems to be caused by simply scrolling the list.

![Screenshot_20220210-181042](https://user-images.githubusercontent.com/35634829/153871682-8fdbccca-5f2d-4859-8d75-f682a0bca716.png)

Android 6.0.1 (with GMS upd. to 21.18.16, cn=M sdk=23)
Webview 97.0.4692.87
Motorola Moto G4
device not rooted

**Comment by uli-on** [comment]
This still happens on my Android 10 phone.

**Comment by alialbaali** [comment]
This has been fixed in 2.1.0.

**Comment by uli-on** [comment]
Yup, this is fixed, woohoo!
