### ISSUE TITLE
Folder colours are invisible in folder options > Edit folder

### ISSUE THREAD

**Issue by uli-on** [alialbaali/Noto#35]
Initially, all folder colors except the chosen one are not displayed, but take up their space as if they were visible. If you tap on them you can make them visible one by  one. Most of them then remain that way, i. e. few dissppear again on scrolling the colour list, which reminds of #34

![Screenshot_20220210-181126](https://user-images.githubusercontent.com/35634829/153872499-a8e432ef-111d-40f3-9207-42c5174d7806.png). 

Noto v2.0.1 (from F-Droid) 
Android 6.0.1 (with GMS upd. to 21.18.16, cn=M sdk=23)
Webview 97.0.4692.87
Motorola Moto G4
device not rooted

**Comment by uli-on** [comment]
This does not happen on my Android 10 phone. Issue can be closed if you deem it obsolete.

**Comment by alialbaali** [comment]
I'll keep this issue open for now to verify no one else is facing it.

**Comment by alialbaali** [comment]
This has been fixed in 2.1.0.
