### ISSUE TITLE
Leaving Noto inadvertedly has become too easy

### ISSUE THREAD

**Issue by uli-on** [alialbaali/Noto#36]
In v2 one can leave Noto without even wanting to just by tapping the back button in a notes list, whereas v1 then still showed you the libraries to choose and that way avoided qiitting. 

So, either the old v1 behaviour could be a selectable option in settings, similar to the way @TheAngusBurger desires for app *starts* (in #32) , or the bottom drawer opens on tapping back in a notes list, or it should need *two* taps on the back button to close Noto.

**Comment by alialbaali** [comment]
I might add an option to enable double back tap.

**Comment by alialbaali** [comment]
The app now will navigate to "All Folders" before exiting the app in version 2.1.0.

**Comment by uli-on** [comment]
Thanks, that solves my "feeling kicked out" ;)
