### ISSUE TITLE
Selecting text is almost impossible in certain cases with new version

### ISSUE THREAD

**Issue by rancidfrog** [alialbaali/Noto#39]
When selecting text from bottom of the screen on longer notes, text overlaps keyboard, causing difficulties in selecting.
I.E.
Here is a somewhat long note,
![](https://i.imgur.com/0Te5XRE.jpg)

Trying to select last word is impossible, due to keyboard clashing with new app scroll which only happens on recent update,
![](https://i.imgur.com/oDsc52J.jpg)

![](https://i.imgur.com/CuN6pCF.jpg)

The new version libraries has bugs or specific properties that need to be set

**Comment by alialbaali** [comment]
This has been fixed in 2.1.0.

**Comment by alialbaali** [comment]
Are you still facing this issue @rancidfrog?

**Comment by alialbaali** [comment]
I'm closing this as it has been fixed, and there's no response from the author.
