### ISSUE TITLE
Reminders: Adding note reminder fails if you haven't exited the note first

### ISSUE THREAD

**Issue by WTechNinja** [alialbaali/Noto#4]
So, I've noticed this a couple of times, if you make a note and then try to add a reminder without exiting the note first it won't make the reminder (at least on my device)

Steps to reproduce:
Make a note, add some random text to it
Without leaving the note, try to add a reminder
Pick the time and date and hit "Ok"

Tada, there is still no reminder listed. If you leave the note and go back in it'll work just fine, though.

**Comment by WTechNinja** [comment]
Also, maybe related, if you're editing a note and then hit Home or Recents (with Noto still in the editor) and mess with other things and Noto gets killed by something after a bit, the note is gone because it wasn't saved. It'd be nice if it autosaved after you stopped typing for a couple of seconds or something similar.

**Comment by alialbaali** [comment]
Thank you for the feedback!

Both issues have a single solution, so in the next release notes are gonna be saved automatically after 250 milliseconds.

**Comment by alialbaali** [comment]
Check version `1.3.5` and let me know.

**Comment by WTechNinja** [comment]
It works beautifully, thanks again. Both problems are solved.
