### ISSUE TITLE
Issue in notes concerning folder title, labels, info line, influenced by keyboard height and/or toolbar(s)

### ISSUE THREAD

**Issue by uli-on** [alialbaali/Noto#40]
For replicating, open a long note, activate a keyboard that has a top toolbar, open it and fold it back in. 

- with your keyboard closed, scroll to the very bottom of your long text.
- place the cursor inside the last word. Result: the keyboard opens, the shrunk folder title disappears. If that's intended: no complaint, more space for writing. But: the folder title remains when you click lines in the **upper** part of the screen. 
- now scroll to the top of the text and - once there - pull downward. The folder title does not reappear. Depending on the keyboard height and the number and height of keyboard toolbars, the header elements (i.e. folder title, date of creation, word count, and labels) are more or less hidden: the more space the keyboard takes up, the less of of the note header elements are displayed. 

Experiment with other keyboards/heights/number or display of toolbar(s). The header area's visibility will change. 

BTW: In case you change the keyboard height in one way or another, or add or remove toolbars, or switch from one keyboard to another one, you'll have to close and re-open the keyboard in order to have initial test conditions (removes height calculations of previous states).

Might be related to #37 and #39.

**Comment by alialbaali** [comment]
Please check if you're still having this issue in 2.1.0.

**Comment by uli-on** [comment]
That's also fixed. Great! I'll close this one, too.
