### ISSUE TITLE
Feature Request: Add option to disable animation

### ISSUE THREAD

**Issue by AlbahrawyTiger** [alialbaali/Noto#43]
I always disable animations from developer options, Noto overloads animations where there is conflict and clutter on the screen because of this and sometimes lag, can I add an option to disable the animation or fix this.Thank you

**Comment by uli-on** [comment]
I'd second this one. Over time there have been too much animations added to the app, especially around labels. They happen even where an animation does not make sense, like when closing a note with no changes on labels, or even no changes at all. Likewise: during scrolling up and down a folder. 

Animations might even cause the issue reported in #34.

**Comment by uli-on** [comment]
@AlbahrawyTiger Do you happen to have Nunito activated as your font? If so: Can you please have a look at #45 and see whether you can confirm that behaviour, please? TIA!

**Comment by AlbahrawyTiger** [comment]
> see whether you can confirm that behaviour, please? TIA!
It didn't happen to me so I can't confirm it

**Comment by AlbahrawyTiger** [comment]
> and see whether you can confirm that behaviour, please? TIA!

It didn't happen to me so I can't confirm it

**Comment by alialbaali** [comment]
I'll work on a fix.

**Comment by alialbaali** [comment]
@AlbahrawyTiger Are you still facing this issue?

**Comment by AlbahrawyTiger** [comment]
@alialbaali No, it has been resolved in the new version Thank you
