### ISSUE TITLE
Noto crashes when opening phone data, what's the matter?!

### ISSUE THREAD

**Issue by AlbahrawyTiger** [alialbaali/Noto#44]
Noto crashes when opening phone data, big lag occurs and sometimes force stops, and when data is closed, Noto works again well, how does this happen and what does Noto have to do with phone data?!

OPPO A15
Android 10
Total RAM usage 50% of 3GB

Big lag when phone data is on and sometimes force close
![Screenshot_2022-02-25-10-33-19-73](https://user-images.githubusercontent.com/61330601/155685411-6b57326a-752c-4eae-8027-c8b6a4bfd9c7.jpg)

When the phone data is turned off, Noto works fine
![Screenshot_2022-02-25-10-33-50-35](https://user-images.githubusercontent.com/61330601/155685758-49e76599-284e-4d66-8102-d6c096a3a0c5.jpg)

**Comment by uli-on** [comment]
Like you, I've experienced Noto freezing (see #18). But you seem closer to finding the source. I'd like to test whether I can replicate your issue, but I must confess I don't understand what your point is when you say "opening phone data". Do you mean a connection, i.e. you'd have no problem when flight mode is on? Or do you have a phone number in your note?

**Comment by AlbahrawyTiger** [comment]
> Do you mean a connection, i.e. you'd have no problem when flight mode is on? Or do you have a phone number in your note?

No, it has nothing to do with flight mode or phone number in note, this only happens when you open the internet data connection (see the notification bar above the screenshot
