### ISSUE TITLE
Label animation is font dependent

### ISSUE THREAD

**Issue by uli-on** [alialbaali/Noto#45]
When scrolling through a folder of notes, with *Nunito* activated, the labels rise bubbling into view. With *Monospace* activated there's no such thing happening. At least muuuuch less often: Almost all of the notes come into view with static, fixed label positions. Only at the list ends there's one or two animations taking place after scrolling very quickly, namely while the list end's springing effect is happening.

If I'd have a choice, I'd be much in favour of having the option to switch animations off completely, in any view, any pane, like I commented already in #43.

Noto v2.0.1 (from F-Droid) 
Android 6.0.1 (with GMS upd. to 21.18.16, cn=M sdk=23)
Webview 98.0.4758.87
Motorola Moto G4
device not rooted

**Comment by alialbaali** [comment]
Label animations have been disabled in version 2.1.0.

**Comment by uli-on** [comment]
This isn't an issue anymore since you've reduced label animation drastically.
