### ISSUE TITLE
can't find grid layout modes

### ISSUE THREAD

**Issue by wu4339** [alialbaali/Noto#52]
can't find grid layout modes in version 2.1.1

**Comment by alialbaali** [comment]
For folders or notes? Can you please share a screenshot, or better describe what's the problem?

**Comment by wu4339** [comment]
ok, I've found it，only the general floder has grid layout mode ,not easy to find the setting。

**Comment by alialbaali** [comment]
All the folders should have list/grid modes, except "All Notes" and "Recent Notes".
