### ISSUE TITLE
Label filtering of type "Exclusive" stopped working and got into some kind of "very strict mode"

### ISSUE THREAD

**Issue by uli-on** [alialbaali/Noto#56]
I found label filtering was working completely different than expected. I always use label filtering set to exclusive type. This time, however, none of my notes are displayed after applying one, two, or several of the label filters. Currently, the only way I can filter and display certain notes, is to apply exactly ***all*** labels the notes have set, like I have to find the intersection/overlap on my own, but that's of course no way to work with Noto. 

I absolutely don't have any idea what might have caused this. I observed it for the first time in a v2.1.1. It was fixed on an interim basis for some hours, after I installed v2.1.2 but came back to life again, unfortunately. I've tried already to uninstall 2.1.2, install 2.1.1 and import an export file, then update to v2.1.2, but no success.

**Comment by alialbaali** [comment]
_Exclusive_ label filtering will match only the notes that contain all the selected labels. However, _inclusive_ label filtering will match any note that has any of the selected labels.

**Comment by uli-on** [comment]
In order to be sure you understand:

My example article has two labels applied.

Noto v1 displayed that article already when I selected one of the labels that was applied to it, regardless whether it had two labels applied.
Noto v2.1.1 and 2.1.2 did exactly that until the error occurred. CURRENTLY it displays zero articles when I have only one label filter set and it shows my article only when I set EXACTLY the two that are applied to my article.

**Comment by alialbaali** [comment]
> Noto v2.1.1 and 2.1.2 did exactly that until the error occurred. CURRENTLY it displays zero articles when I have only one label filter set and it shows my article only when I set EXACTLY the two that are applied to my article.

Is label filtering set to inclusive or exclusive?

**Comment by uli-on** [comment]
Exclusive.

**Comment by alialbaali** [comment]
Then that's the expected behavior. 

By default, each folder label filtering is set to inclusive, which is/was always the case even when the option wasn't there (before 2.1.0). 

I don't quite get the problem yet. Could you please let me know what is the expected result when label filtering is set to inclusive or exclusive? I might have got them mixed up in the implementation.

**Comment by uli-on** [comment]
I think inclusive filtering is working OK. (You select a label and all articles with that label are listed. You select a second label and all articles with that label OR the second label OR both labels are listed.) But this issue is ***not*** about inclusive filtering type!

Exclusive listed all notes with the selected label applied. All notes(!), while now it lists none. Exception: there is a note with ***exactly that*** label applied and not a second one or more. After adding a second filter, Noto subtracted all notes that hadn't these two labels applied, i.e. it was displaying notes with both labels applied, A ***AND*** B.

Because almost all my notes have multiple lables applied, with current/broken behaviour, I almost always have an empty filtering result, zero notes displayed, unless by a lucky accident I happen to select exactly those labels that match my note.

**Comment by alialbaali** [comment]
I'm sorry Uli, I'm finding a hard time understanding the issue. You're basically explaining how it should work. I don't see any problem there. Exclusive label filtering displays only notes that have **ALL** the labels applied, and omits everything else, including the notes that had **only** one of the labels but not the others.

For example, let's say you have three labels "A", "B", and "C". And you have 4 notes, one labeled with **only** "A", the second labeled with **only** "B", the third labeled with "A" **and** "B", and the forth labeled with "A", "B", and "C". Like so:

- Note1 [A]
- Note2 [B]
- Note3 [A, B]
- Note4 [A, B, C] 

Where [*] is the labels each note have.

Now, with Exclusive label filtering.

- If you select **only** A, you only get Note1, and nothing else.
- If you select **only** B, you only get Note2, and nothing else.
- If you select **only** A **And** B, you only get Note3, and nothing else.
- If you select All the labels A, B, and C, you only get Note4, and nothing else.

That's how Exclusive label filtering currently works. There could be another way, and _now_ I think that's what you're talking about. The other way, it would be like this:

- If you select **only** A, you only get Note1, and nothing else.
- If you select **only** B, you only get Note2, and nothing else.
- If you select **only** A **And** B, you only get Note1, Note2, and Note3.
- If you select All the labels A, B, and C, you get all the notes, Note1, Note2, Note3, and Note4.
 
Is this the issue? Or is it something else?

**Comment by uli-on** [comment]
I hate doing screen recordings. But probably better to demonstrate it that way. Please note that the second and third note also have the same first label as the demo note.


https://user-images.githubusercontent.com/35634829/179429916-18656544-ea8c-4580-adbf-8e341e0d36ad.mp4

**Comment by alialbaali** [comment]
Have you checked my previous comment?

**Comment by alialbaali** [comment]
Would you like to see a build where Exclusive label filtering is implemented a bit differently (like in my previous comment)? @uli-on

**Comment by uli-on** [comment]
I'll gladly try, but have a look at the screenshot I just prepared in v1.8. That's how label filtering worked for me and why I praised Noto for its unique filtering in #38.

![Screenshot_20220718-153340](https://user-images.githubusercontent.com/35634829/179539165-c63234cc-c648-4411-904e-d87bb2d2b3db.png)

Currently, in v2.1.2 the note titled 1, 2, 3 would not be displayed.

**Comment by alialbaali** [comment]
This is the same way it has always been. In 2.1.0 and later, it is called "Inclusive". So if you want it the same way as before, you can just set it to "Inclusive". 

But you mentioned "Inclusive" filtering is not the problem. So, here's a build you can try with a slightly different implementation for "Exclusive" label filtering:
[Noto-debug.zip](https://github.com/alialbaali/Noto/files/9138570/app-debug.apk.zip)

**Comment by uli-on** [comment]
I've installed the test version, and I must say "exclusive" mode works pretty awesome now! Like it's always been like that. If you would include this filtering mode into the next version I'd be very happy and close this topic forever ;) Thanks!

**Comment by alialbaali** [comment]
That's good to hear. 

> Like it's always been like that. 

What do you mean by that? Because, "Exclusive" mode has been added only recently in version 2.1.0

**Comment by uli-on** [comment]
It feels "at home". Thanks for your efforts!

**Comment by alialbaali** [comment]
You're welcome! 

You didn't answer my question though :)

**Comment by alialbaali** [comment]
Also, do you think the other behavior should be also added as in option label filtering? 

Maybe it would be called like "Same" or "Exact match", what do you think?

**Comment by uli-on** [comment]
Yes, add it as third option,it might help some structured minds filtering out results quicker. "Exact match" sounds self-explaining. BTW, the German translation, "Genaue Übereinstimmung", is much longer than English.

**Comment by alialbaali** [comment]
How about "Strict"? @uli-on

**Comment by uli-on** [comment]
That's so concise that it'd need a string of clarifications ***above*** the buttons on what's actually meant. But what I  wanted to point out is: can the button text fields perhaps be made self-expanding?

**Comment by uli-on** [comment]
Or hyphenation?

**Comment by alialbaali** [comment]
The text can be self-expanding. But, I personally prefer "Strict" more.

**Comment by alialbaali** [comment]
Version 2.1.3 is out now.

**Comment by uli-on** [comment]
Tested and enjoyed. Thanks!
