### ISSUE TITLE
Bug: Add note reminder button doesn't change

### ISSUE THREAD

**Issue by WTechNinja** [alialbaali/Noto#6]
After you add a new reminder, the floating "Add reminder" button on the bottom right doesn't change into the "Modify reminder" button until you exit the note and reenter it.
App version: 1.3.5

Steps to reproduce:
1. Enter a note
2. Add a reminder
3. Tada, the button should still be the "Add Reminder" button, despite there now being a reminder.

If you exit and reenter the note, the button will be the correct one, though.

**Comment by alialbaali** [comment]
Thank you for the report!

This issue should be fixed in the next release.

**Comment by WTechNinja** [comment]
Fixed. Thanks
