### ISSUE TITLE
Edited notes aren't always saved [REQUEST FOR USER OBSERVATIONS]

### ISSUE THREAD

**Issue by uli-on** [alialbaali/Noto#60]
In v2.1.2 I've experienced, that I had to edit my notes several times until my corrections were saved. I think it might happen especially often reopening an already saved fresh article for the first time, but I didn't keep a record.

**Comment by alialbaali** [comment]
Does this happen frequently? @uli-on

**Comment by uli-on** [comment]
I've had it 6 times now, and only in v2.1.2 (but maybe already in 2.1.1),
so could have to do with the undo/redo mechanism. It seems to be restricted
to the body field, BTW. (On the other hand: I edit titles far less, so the
chance to find hickups there is far smaller.)

As always: Should I find a way to replicate that reliably, I'll post.

**Comment by uli-on** [comment]
OK, think I have found a way to reliably  reproduce that Not Saving behaviour. 

- Set the folder to open notes in Editor mode. (maybe not necessary, but it's like that here).

- Set the preview to full screen, may be part of the problem, see later on. 

- Open a note

- Open the virtual keyboard by tapping the text. 

- Edit the note, here: Headline and body.

- Open the preview by tapping the related icon

-  Swipe up from the bottom edge of the screen to bring Android's nav buttons back. 

- Press "back" 

- Previous version of the note is back again.

Am I misinterpreting what the back button's expected to do here, i. e. not bringing back the previous version but leaving the current viewing mode?

**Comment by alialbaali** [comment]
Wow, that's hell of a bug, hah 😄?

**Comment by alialbaali** [comment]
Are you still encountering this issue?
