### ISSUE TITLE
Sticky search (can’t escape search mode without changing folder)

### ISSUE THREAD

**Issue by uli-on** [alialbaali/Noto#61]
Steps to reproduce

- (In the label bar, press „All“ in order to stop label filtering)
- Initiate a search. Watch the number of notes decrease.
- For creating same preconditions: open a note, close it again by pushing Android’s back button (can probably be omitted)
- Push the back button again, the search field disappears, the number of notes rises back up to where it’s been previously (i.e. search seems dismissed but isn’t)
- In the bottom toolbar press the three-dot menu, select edit, press „Update folder“ (or select a different colour, then „Update folder“, doesn’t matter)
- Result: The previous search is active again, the notes list is reduced.
- Press Android’s back key: The search can’t be cancelled any longer, the folder drawer is opened instead.

You've to open another folder to escape that "trap".

Tested version: 2.1.2-debug
Edit: version number, typo

**Comment by alialbaali** [comment]
This behavior has been fixed in version 2.1.3.

**Comment by uli-on** [comment]
Yup, done & gone!
