### ISSUE TITLE
Please make selected text's background stand out better against the page colour

### ISSUE THREAD

**Issue by uli-on** [alialbaali/Noto#62]
Although this is slightly irritating already when manually selecting text, I can "work around" it by turning my attention to the selection handles. 

But the disadvantage of this low colour contrast becomes uncontrollable when working with the swiping gesture of delete keys on several virtual keyboards, a proceeding where no handles are being displayed for indicating selection boundaries.
In order to see for yourself, please try one of these three keyboards available from F-Droid:
OpenBoard, FlorisBoard, Simple Keyboard

**Comment by alialbaali** [comment]
Text highlight color should be in version 2.1.3.

**Comment by uli-on** [comment]
Works a treat! Thanks!
