### ISSUE TITLE
Noto 2.1.3

### ISSUE THREAD

**Issue by franco27** [alialbaali/Noto#63]
Hello 

After the update, I can no longer open your app. 

The icon in Android is gone and after installation, the open menu is grayed out 
On the Android window of your app. 

All my notes are blocked without being able to see them. I hope an update will come soon. If I uninstall, I lose everything. 

Xiaomi Redmi 8 
Android Version 10 Android 10 
MIUI
V12.5.2.0.QCNEUXM

Architecture
 64-bit

Instruction sets
arm64-v8a armeabi-v7a armeabi Qualcomm®
Snapdragon™ 439

CPU
4 x Cortex-A53

Cores 8
 RAM size 4 GB

**Comment by franco27** [comment]
In an application manager, when I go to Noto and ask to open your application. 
There is an error message from Android, with written this app is not allowed to run.

**Comment by alialbaali** [comment]
Hi, I'm sorry you're having this issue. Don't worry. I'll try to make sure the app works for you.

Please provide me with the information below:

Are you using the APK version from GitHub?

Did you choose a different icon for the app in the previous versions? 

What Android version are you using?

**Comment by alialbaali** [comment]
Also are you by any chance using a custom launcher?

**Comment by franco27** [comment]
Thank you for your reply 

Yes I use github apks. For previous versions too 

I didn't change the icon. This is the default icon 

Android 10

I use Xiaomi's default launcher

Thanks again

**Comment by alialbaali** [comment]
Okay, could you try installing the APK again without reinstalling the app, and open it directly when it shows you the menu that says "App is installed"?

**Comment by Archeix7** [comment]
Same problem f-droid version

**Comment by alialbaali** [comment]
Did the icon disappear without even launching the app?

**Comment by alialbaali** [comment]
Could you please try with this [APK](https://github.com/alialbaali/Noto/files/9178130/Noto.apk.zip)?

**Comment by franco27** [comment]
> 

I can't.  As I told you, when the installation is complete.  The menu called "open" is grayed out or disabled.

**Comment by alialbaali** [comment]
What about the APK I sent, does it have the same issue?

**Comment by franco27** [comment]
Yes, Same problem 
![Uploading IMG_20220725_075322.jpg…]()

**Comment by alialbaali** [comment]
Please try again with this [APK](https://github.com/alialbaali/Noto/files/9178397/Noto.apk.zip).

**Comment by alialbaali** [comment]
One more thing, do you have Play Store installed? If you do, try to launch the app from there.

**Comment by franco27** [comment]
Yes, the Play Store is installed.  But the "open" button is gone.  So I can't open your app, from PlayStore.  There is only the button to uninstall.

**Comment by franco27** [comment]
Yes with this APK I can now open.  But before it opens, there is a black screen for 1 or 2 seconds.
In the PlayStore, I found the button to open with this APK

**Comment by franco27** [comment]
Many thanks

**Comment by franco27** [comment]
Usually I don't have a black screen, before opening your app.  I opened it several times and each time now there is a black screen (the display lasts 1 or 2 seconds, and after your application opens).  I wanted to report.  Excuse me for not having answered quickly, I try to answer you but I am currently at work.

I didn't have time to look if there were any other problems. I only opened.

**Comment by alialbaali** [comment]
@Archeix7 Are you still facing this issue with the APK I have attached in my previous comment?

**Comment by alialbaali** [comment]
@franco27 Did you use the app before version 2.1.0? The reason I'm asking that is because I have changed the implementation of some part of the app in version 2.1.0, and now with the latest version (2.1.3) I reverted the changes back to the way it was, due to a bug happening in version 2.1.0. So, the black screen was always there in versions before 2.1.0.

Feel free to take your time in responding! And I'm happy that the app is working for you now!

**Comment by alialbaali** [comment]
Could you please try to install this [version](https://github.com/alialbaali/Noto/files/9179421/Noto.apk.zip), and let me know if it still works?

**Comment by franco27** [comment]
I confirm this APK is still working.
I've been using your app since version 1.x

**Comment by Archeix7** [comment]
> @Archeix7 Are you still facing this issue with the APK I have attached in my previous comment?
Yea, it's work

**Comment by Archeix7** [comment]
> @Archeix7 Are you still facing this issue with the APK I have attached in my previous comment?

Working now, thx
