### ISSUE TITLE
Heavy flickering: Notes become inaccessible after rotating the device

### ISSUE THREAD

**Issue by uli-on** [alialbaali/Noto#65]
See video attached. (removed) 

The last frame seems insightful: Although the note opened is from February, the date shown below the note says "just now". The word count is obviously moving either from or to zero, and there are no labels at all, though the folder the note is stored in has some, see first frame. This all looks as if rotating the device creates a new folder & article and inserts the previous text and undos and redos etc. The whole flickering can only be stopped by swiping Noto out of the app switcher.

This happens only in notes' edit mode, BTW, not in preview nor in lists or other places. Also, I could not witness that effect on my old Android 6 Motorola G4, same Noto version.

Noto v2.1.3, Android 10 (Fairphone 3), Webview v102.0.5005.78

**Comment by alialbaali** [comment]
This bug happens when changing the system theme too. It is kinda a known bug, and should've been fixed completely in version 2.1.3. However, I guess it isn't the case yet.

Thanks for reporting it!

**Comment by alialbaali** [comment]
This should be fixed in 2.1.6.

**Comment by afmbsr** [comment]
Great, Fixed it, Thanks

**Comment by uli-on** [comment]
Fixed, here too, for rotation as the trigger. Thanks! See also https://github.com/alialbaali/Noto/issues/109#issuecomment-1207271022 for another trigger. I'll report back.

**Comment by alialbaali** [comment]
Oh, I didn't see that comment. Does it happen with 2.1.6? I think it should be fixed too.

**Comment by uli-on** [comment]
I'll keep my eyes open. There might be more preconditions (note opened in foreground / background / whatnot) so might take some days to be sure.

**Comment by alialbaali** [comment]
Any update on this @uli-on?

**Comment by uli-on** [comment]
Ah, didn't encounter flickering any longer. Can be closed, but I can't do it, I'm logged in with Octodroid, which has no such option yet.

**Comment by alialbaali** [comment]
Great to know.
