### ISSUE TITLE
Version 2.1.3 opens settings instead of the app

### ISSUE THREAD

**Issue by charlag** [alialbaali/Noto#66]
Hi, thank you for the great app.

Unfortunately since the last update instead of seeing the app I see "app info" screen for the app. I know it sounds a little silly but I have no idea what could be causing it. I tried few different ways to open it: home screen, app list, via F-Droid, all the same. Tried force-stopping it too. I see how for a split second a normal activity opens but then it opens settings instead.

Is there any advice you can give?

version 2.1.3 from F-Droid
Android 11, Fairphone 3

**Comment by extropista** [comment]
The exact same thing happens to me with the latest version, and I can't reinstall the previous version as it says "not supported".
Nor can I reinstall it since that would imply losing my notes.

I have a Xiaomi POCO X3 Pro with Android 12 (MIUI 13)

**Comment by alialbaali** [comment]
Do you mean the app settings, or system settings?

**Comment by alialbaali** [comment]
Have you downloaded the app from Google Play Store or GitHub?

**Comment by charlag** [comment]
![Screenshot_20220728-084920](https://user-images.githubusercontent.com/3099142/181439472-9936ac9c-ca13-4e54-a873-ca53e3b81bca.png)

This is what I see

I downloaded from F-Droid

**Comment by alialbaali** [comment]
This issue is [known](https://github.com/alialbaali/Noto/issues/63), and an update has been published two days ago. Please update your app.

**Comment by charlag** [comment]
2.1.3 is the latest release and that's what I'm using?

**Comment by alialbaali** [comment]
The fix is published with the same release version. Play Store should let you update the app. However, if you have downloaded the app from F-Droid, and F-Droid isn't showing the update, then you can download the update from the [Releases](https://github.com/alialbaali/Noto/releases/tag/v2.1.3) page on GitHub.

**Comment by charlag** [comment]
Hi, I'm afraid this won't work, F-Droid builds and signs the app on their own.
It came to my attention that I got it not from an official F-Droid repo but from IzzyOnDroid one. I am not sure how it is set up to update but it might be by tag. I will ask the owner of the repo about the update. Would you be open to making a release tag with a patch version?

**Comment by alialbaali** [comment]
Yeah, I haven't published the app to F-Droid myself. I can make a new tag if you want, no problem at all!

**Comment by charlag** [comment]
It will probably also require version code bump, I'll try to figure it out, thank you for the responses!

**Comment by alialbaali** [comment]
Have you tried downloading the updated APK?

**Comment by charlag** [comment]
I asked the author and here's the response:
https://mastodon.technology/@IzzyOnDroid/108723826744379377

Turns out this repo doesn't build the app, just fetches the APK so I could just update from the releases page which I did and it works. Sorry for the noise!

**Comment by alialbaali** [comment]
No problem! I apologize for the inconvenience. 

@extropista Could you please update the app from the Releases page, and let me know if it works for you?

**Comment by extropista** [comment]
Hello @alialbaali thanks for your reply, ..after following the thread of the conversation, I have reinstalled the app by downloading the file in the github releases, which has worked for me too.

(I already had the same version installed, 2.1.3, but I guess it happened when updating from Droid-ify with the Izzyondroid repository)


Greetings and thanks for everything!

**Comment by alialbaali** [comment]
Glad it is working for you!

**Comment by IzzySoft** [comment]
> It will probably also require version code bump

Without that, Android won't recognize it as update, right. But at least as long as the `versionCode` was not *decreased,* it still allows a manually forced update (e.g. `adb install -r app.apk`).

As pointed out at Mastodon, my updater looks for *new* tags – in your case: the tag name should indicate a higher `versionName` and should match that of the attached APK, then it will be picked up within 24h.
