### ISSUE TITLE
Undo/Redo buttons and their history are black

### ISSUE THREAD

**Issue by afmbsr** [alialbaali/Noto#67]
This happens with the light theme when the New Note Shortcut window is opened two or more times in a row

![Screenshot_٢٠٢٢٠٧٢٨-٢٣٠٦٥٢_Noto](https://user-images.githubusercontent.com/38974362/181681775-9303e0ef-872f-466b-a0e7-d908ebb2935b.png)

**Comment by alialbaali** [comment]
Can't reproduce. Do you have any additional info?

**Comment by afmbsr** [comment]
- Change the appearance of the application to light. 
- Add (new note shortcut) to the home screen.
- Open a blank note by The shortcut.
- Close the blank note.
- Open a new note again through the shortcut, and write some text.

 Result: Undo/Redo buttons and their history buttons turn black.


https://user-images.githubusercontent.com/38974362/182009988-af041657-db06-4fc0-b590-21d3928cbb46.mp4

**Comment by afmbsr** [comment]
Fixed it, Thanks
