### ISSUE TITLE
Redesign settings screen

### ISSUE THREAD

**Issue by alialbaali** [alialbaali/Noto#70]
The current settings screen is too bloated, and ugly. The new settings screen will be customized by categories (sub-settings), it will include a description for some properties,  and it will show currently set value for properties that has various states such as themes, languages, and icons.

**Comment by SimoneG97** [comment]
I just wanted to add a thing since I've got a suggestion that kinda falls in this one.
How about credit translators in its page that doesn't need translations (e.g. like Infinity)?
For reference, in the "Info" section of the settings:
![photo_2022-08-01_19-32-18](https://user-images.githubusercontent.com/38068023/182208453-e1cd4ad3-621d-428c-aff1-defbb47edd4f.jpg)
(Sorry, couldn't change from Italian to English, but i'll translate the important parts)
There's a section "Traduzione [...] Grazie a tutti i contributori" (Translation [...] Thanks to all contributors) where it has a simple list with the translators inside with associated language flag:
![photo_2022-08-01_19-32-26](https://user-images.githubusercontent.com/38068023/182208802-bf5525d1-3f8f-41d3-9a54-43d532451a35.jpg)
This way is much easier to update it and doesn't require a new translation each time a language is added (and less possible string length problems).

**Comment by alialbaali** [comment]
Really great suggestion!

**Comment by alialbaali** [comment]
This is what I've managed to do. Thoughts? And which version do you like more?

![Screenshot_20220803-050535_Noto Debug.jpg](https://user-images.githubusercontent.com/37933889/182508829-442331ac-c0fc-4702-8256-e8a84a7835bc.jpg)

![Screenshot_20220803-050601_Noto Debug.jpg](https://user-images.githubusercontent.com/37933889/182508845-4f581abf-cd19-4c1a-8fa8-4b7aabd591b2.jpg)

**Comment by SimoneG97** [comment]
I think the first one is better, but with the language written in its appropriate language.
For example, instead of:
- Turkish
- German
- Spanish
- French
It should be (hope I didn't fuck up something):
- Türkçe
- Deutsch
- Español
- Français

And I would add the respective nation flag near the name of the language, just to make it a bit less monotone and/or easier to read (I guess even emoji flags could do the trick).

**Comment by alialbaali** [comment]
Any thoughts @afmbsr, @uli-on, @JustNaturalCake?

**Comment by JustNaturalCake** [comment]
> This is what I've managed to do. Thoughts? And which version do you like more? I personally like the last one.
> 
> ![Screenshot_20220803-050535_Noto Debug.jpg](https://user-images.githubusercontent.com/37933889/182508829-442331ac-c0fc-4702-8256-e8a84a7835bc.jpg)
> 
> ![Screenshot_20220803-050601_Noto Debug.jpg](https://user-images.githubusercontent.com/37933889/182508845-4f581abf-cd19-4c1a-8fa8-4b7aabd591b2.jpg)

The last one looks good yeah

**Comment by JustNaturalCake** [comment]
Personally having not any categories is not a huge deal since i often dont touch the settings menu i only went through once (sometimes updating vault password but thats it really) i feel like a list worked nicely just going through one by one

**Comment by JustNaturalCake** [comment]
I could see it looking fantastic and a new refreshing settings menu sounds great

**Comment by JustNaturalCake** [comment]
I wont lie it looks bloated indeed

**Comment by uli-on** [comment]
> Any thoughts [...] @uli-on [...]

Re "Redesign of the Settings screen"? I don't see such a bad need. Yes, there's this group of "miscellaneous" stuff at the bottom that still comes labeled as "Settings", but on that whole page there's topical order by groups of themes, there's optical structure by dividers, there's icons as bullet points to not make the whole look like a desert of letters. Honestly: I've seen worse (Fair Email, I'm looking at you).

Re Translators page? I support @SimoneG97's proposal: 
- Türkçe: names here
- Deutsch: names here
- Español: names here
- Français: names here etc.

> I guess even emoji flags could do the trick

Here's the bad counter-example (too little distance between lines, making the background colour between flags look like additional horizontal stripes of the flags themselves):

![emoji-flags](https://user-images.githubusercontent.com/35634829/183526755-c30eb5f4-73e1-4cba-8b9f-4ef18d75a531.jpg)


Your favorite, Ali, (see below) is too repetitive, IMHO (DRY ;)

> ![Screenshot_20220803-050601_Noto Debug.jpg](https://user-images.githubusercontent.com/37933889/182508845-4f581abf-cd19-4c1a-8fa8-4b7aabd591b2.jpg)

**Comment by alialbaali** [comment]
@uli-on Just because it isn't that bad, doesn't mean it's good. None of the previous redesigns were actually a "redesign", they were barely any design improvements (adding dividers, changing background color). This redesign will feature some really good changes, such as, Translators, Reading Mode, Vault, etc… will have their own page.

The reasons I'm doing it like this is because:
1. Each translator will have their own role.
2. Clicking on the translator name, would direct the user to the translator's website.
3. There can be multiple translators for a language at the same time. 

There will be a beta release, so you can see it in action, before it gets published.

**Comment by JustNaturalCake** [comment]
Sound good, excited to see the new settings redesign :)

**Comment by alialbaali** [comment]
One more thing I'd like to discuss is whether using sentence case or Title Case when displaying text in different layouts.

**Comment by uli-on** [comment]
Isn't that the job of translators? Or am I misinterpreting you?

**Comment by alialbaali** [comment]
I don't think so. If it is Title Case for one language, then all the languages should be like that. That way, it is more consistent.

**Comment by uli-on** [comment]
OK, so I understood you properly still. Enforced title case would produce orthographic faults in e.g. German and French languages, while it's appropriate for English. Just my 2 cents.

**Comment by alialbaali** [comment]
Okay then, I'll keep it sentence case.

**Comment by alialbaali** [comment]
Which sounds better "Main interface", "Start destination", or something else?

**Comment by uli-on** [comment]
I've been pondering, too, for quite a while how to name it in German. Not an easy one. 

From these two I'd prefer "Main interface". What do you think of "Default folder"?

**Comment by alialbaali** [comment]
The thing with "Default folder" is that it doesn't signal what it does. Meaning, it could be used for anything. For example, I have already used "Quick note folder", as it is more expressive this way. See #64.

**Comment by alialbaali** [comment]
How about this? 
![IMAGE 2022-08-28 06:54:10](https://user-images.githubusercontent.com/37933889/187056607-1210786b-ba67-49bb-b57c-b24602cae237.jpg)

Also, should I keep the flag aligned to the end (like in the screenshot), or next to the language?

**Comment by AI-IMED** [comment]
Instead of the flag, I suggest adding the translation percentage in place of the flag for each language as in Crowdin and including the incomplete languages ​​as Russian, I think this method will motivate users to complete translations into their own languages

**Comment by SimoneG97** [comment]
Looks good to me, probably better if the flag is aligned next to the language as you suggested.

**Comment by uli-on** [comment]
This is how the General Settings screen looks like on my device.


![Screenshot_20220830-172621](https://user-images.githubusercontent.com/35634829/187483434-b71c6cb8-1c8a-4842-a93d-40f5387e5174.png)

I see the following issues:
- Wrapped lines cause vertical misalignment if the counterpart on the other column consists of only one line
- Wrapped lines in column 2 become left-aligned
- No hyphenation, existing hyphens are not used as break points, in-word-wrapping on orthographically wrong places 
- Distance between columns is too small in case strings would take full column width 
- Distance between option switch and its text label is quite tight (can be tested with the "Remember scrolling position" switch in English)
- Repositioned/reused string for theme selection (dark/light etc) repeats the term from column 1 (all languages concerned)

**Comment by alialbaali** [comment]
1. Don't you think the value should be vertically centered when the option (in first column) is multiline?
2. Is right alignment better, or should I move the value to the bottom of the option?
3. Hyphenation isn't possible in the UI kit I'm using ([Compose](https://developer.android.com/jetpack/compose/)). Check [this](https://stackoverflow.com/questions/72571133/how-to-use-soft-hyphen-in-jetpack-compose) and [this](https://stackoverflow.com/questions/68655165/break-sentence-line-with-hyphen-if-word-is-too-long-in-android-jetpack-compose).

As for the others, I'm working on them.

**Comment by uli-on** [comment]
1 No, honestly not. Unfortunately, the current implementation creates clutter and visual confusion, because it doesn't take advantage of viewing and reading habits. A line of text serves the eye also as a visual guide from one column to the next one. This should be utilised and it would even remove some visual clutter, as a bonus. 

2 That right alignment is one more means that creates clutter. In my last post above I didn't want to bitch about everything that's opposed to reading habits but you explicitly ask me about right-alignment. 
So: No, please, if you want by all means to stick with a two column arrangement, which is not ideal for small screens in my POV, then please set both columns to be left-aligned, it's much more readable in LTR languages and it can be skimmed quicker. That combined with top(!) alignment (not bottom) creates visual calming. Sorry, the graphic designer in me.

3 Thanks for these links, they make clearer what might be going on and why.

**Comment by alialbaali** [comment]
Any issues on Beta2?

**Comment by uli-on** [comment]
In the line for "Main Interface", the minimum gap between col1 and col2 is (can become) almost as tight as a blank character:

![Screenshot_20220915-152555](https://user-images.githubusercontent.com/35634829/190431884-b7b8db68-c842-4485-836a-17f0c0dc61c1.png)

Else: no issue, rather design consistency, where you place icon-sized logos and flags right aligned, but have icons left aligned in the previous screen. The logos might also serve as bullet points and help guiding the eye, while currently the view is constantly jumping from left to right.

**Comment by alialbaali** [comment]
The thing is about icons being left/right aligned, is that, some options might not have an icon (such as version, license, credits, etc...).

If I move the icons to the left, the text moves to the right a bit, while the ones without icons would stay to the right. Which is definitely inconsistent. 

Take for example this image from the Sync app:

![IMAGE 2022-09-18 20:20:04](https://user-images.githubusercontent.com/37933889/190920077-74dee7c5-9e2c-4920-99ef-4105ed02e482.jpg)

Due to that, there are two possible solutions:

1. Make them right aligned. Like how they're currently implemented.
2. Make them left aligned, while leaving an empty space in the beginning of the option when it doesn't have an icon.

**Comment by alialbaali** [comment]
>     * Türkçe
>     * Deutsch
>     * Español
>     * Français

From where do I get the translations of the languages like the ones above? Or should I just Google Translate it? Or make the languages translatable and access their localized values from code.

@uli-on @SimoneG97

**Comment by SimoneG97** [comment]
To be honest I just searched them (in particular https://omniglot.com/language/names.htm and https://www.internationalphoneticalphabet.org/languages/language-names-in-native-language/)
but making it translatable doesn't sound like a bad idea, in case its hard to find them.

**Comment by uli-on** [comment]
I can highly recommend deepl.com, but would ditch Google Translate completely.

**Comment by alialbaali** [comment]
Great suggestions. However, deepl.com only covers few languages, which is enough for now, but not for the future.

Here's how it looks now:

![IMAGE 2022-09-18 22:54:06](https://user-images.githubusercontent.com/37933889/190925862-7bc57ccb-8e14-43fc-960f-aa54f4539021.jpg)

![IMAGE 2022-09-18 22:54:08](https://user-images.githubusercontent.com/37933889/190925864-1969b3d7-3b12-4b66-bca5-ce252b03e13f.jpg)

**Comment by uli-on** [comment]
> Make them left aligned, while leaving an empty space in the beginning of the option when it doesn't have an icon.

This! It's cleaner with the solidly aligned strings stacked upon each other. I waited for my structural memory to return, where I might have encountered such an example in the last few days so I could post a screenie, but can only ask you to rely on my visual memory and my imagination, which are faaar better ;-)

**Comment by alialbaali** [comment]
Of course!

**Comment by alialbaali** [comment]
Does that mean I should bring back icons in options in the nested screens?

**Comment by uli-on** [comment]
Which ones are gone, anyway?

**Comment by alialbaali** [comment]
Most of them, except the first screen.

**Comment by alialbaali** [comment]
The thing is, after thinking about it more, isn't that the right aligned icons are only done in the About settings and nowhere else. So, is it really necessary to include empty space in most options when no icons are included? And even if some include icons, wouldn't that make the UI more complicated. 

What do you think?

**Comment by uli-on** [comment]
When there's no icon at all, I'd not leave space! If there *are* icons, however, even a single one, it'd look untidy without the separate column. Your screenie from Sync is different in that it has both sorts strictly separated. That's a rare case.

**Comment by alialbaali** [comment]
Like this?

![IMAGE 2022-09-22 14:47:04](https://user-images.githubusercontent.com/37933889/191738564-d011db88-3504-471d-a0f0-a9941d8baef1.jpg)

**Comment by uli-on** [comment]
Yes, that's looking tidy and clean, and guides the view without bothering the ocular muscles :)

**Comment by AI-IMED** [comment]
@alialbaali, Please correct the settings layouts in the places shown in the pictures

![٢٠٢٢١٠٠٢-١٤٣١٤٥](https://user-images.githubusercontent.com/38974362/193455606-d135c65f-8fa7-4e20-9734-55489f06e303.jpg)

**Comment by AI-IMED** [comment]
Thanks @alialbaali , only the notes font list remains.


![Screenshot_٢٠٢٢١٠١٦-١٠٢٧٤٩_Noto](https://user-images.githubusercontent.com/38974362/196023726-2438354f-610c-44cc-ba14-575bac874632.jpg)

**Comment by uli-on** [comment]
Please have a look at the General settings in an emulator set to smaller screen, e.g. my 1080 x 2016, 480 dpi, 3x. Here are some screenshots taken with Czech and German languages. E.g. there's not enough room for switches *and* complete label (some letters are covered by the switches), the quick notes folder name is pushed to the very edge (German) or even to outside of the screen (Czech) thus creating a huge empty gap.

![Screenshot_20221014-064515](https://user-images.githubusercontent.com/35634829/196708458-ca92f39a-19f5-40cb-99bb-ba029bb9780e.png)

![Screenshot_20221014-064527](https://user-images.githubusercontent.com/35634829/196708522-b0bbc170-2e02-48d0-b4f3-52f88430d5df.png)

![Screenshot_20221014-064602](https://user-images.githubusercontent.com/35634829/196708655-0b84c4f1-ebc4-4699-85e6-11385ae9f1d2.png)

![Screenshot_20221014-064632](https://user-images.githubusercontent.com/35634829/196708732-7964083a-e983-46d2-b4d1-af2e1e5a4f55.png)

**Comment by alialbaali** [comment]
2.2.0 has been released to the public. There are many issues that have been created for this release, so can you please close any issue which is complete or you don't have any suggesting about it (Including this issue)? Thank you.

**Comment by alialbaali** [comment]
Any update?

**Comment by SimoneG97** [comment]
Nothing weird to report on my side, everything looks good and works! (except me missing in the translators list but you already know this 😛 )
