### ISSUE TITLE
Search in notes

### ISSUE THREAD

**Issue by alialbaali** [alialbaali/Noto#73]
This feature would allow you to search specific words in notes. You would be able to cycle though them, just like in browsers.

**Comment by uli-on** [comment]
That's great and on my wishlist, too. Do you think it's possible to search through a folder and open single findings and then have the search terms still marked, without initiating a new search inside the note? That'd be *really* awesome!

**Comment by uli-on** [comment]
I think one of the open source apps it has is Neutrinote.

**Comment by alialbaali** [comment]
> That's great and on my wishlist, too. Do you think it's possible to search through a folder and open single findings and then have the search term still marked, without initiating a new search inside the note? That'd be _really_ awesome!

That's definitely something I'd do when supporting search in notes.

**Comment by alialbaali** [comment]
@uli-on 

<details>
<summary> Spoiler Alert </summary>
This feature will be supported in 2.3.0. Stay tuned for the beta!
</details>

**Comment by alialbaali** [comment]
Any suggestions regarding this feature?

**Comment by uli-on** [comment]
Generally I'm very happy that Noto has a more comprehensive search, now :)

If that's possible, though, technically, and only because you asked: Initiating a search from one of the virtual folders (All, Recent, Scheduled, Archived) would be most helpful for situations where one can't remember at all where one's written on certain topics, was it the "News" folder, the "General Software Dump", "Security" or one of the specific app related ones, and which of these 17? I know, searching is possible from these, but I have to start a new search inside each result, time and again.

One small concern is the use of folder colour for highlighting search terms. Currently, there are two folder colours making it hard to spot the search results, the pure white in the dark theme, (which parallels the pure black in the white theme), and esp. the light gray. Hence, if this is technically possible I'd be for applying a background colour to search terms like used for word selection.

Oh, and if the transparent space between the search field and the keyboard (Noto toolbar, respectively) could be minimised (maybe full width for design reasons), that would be awesome. Try a dark theme where you have no search box shadow for making the distance aesthetically appealing, then while scrolling you have the content flickering through between these elements which is both unattractive and distracting.

**Comment by alialbaali** [comment]
> If that's possible, though, technically, and only because you asked: Initiating a search from one of the virtual folders (All, Recent, Scheduled, Archived) would be most helpful for situations where one can't remember at all where one's written on certain topics, was it the "News" folder, the "General Software Dump", "Security" or one of the specific app related ones, and which of these 17? I know, searching is possible from these, but I have to start a new search inside each result, time and again.

I missed implementing this. But, it's going to be in the next beta.

> One small concern is the use of folder colour for highlighting search terms. Currently, there are two folder colours making it hard to spot the search results, the pure white in the dark theme, (which parallels the pure black in the white theme), and esp. the light gray. Hence, if this is technically possible I'd be for applying a background colour to search terms like used for word selection.

Great suggestion! I'll work on it now.


> Oh, and if the transparent space between the search field and the keyboard (Noto toolbar, respectively) could be minimised (maybe full width for design reasons), that would be awesome. Try a dark theme where you have no search box shadow for making the distance aesthetically appealing, then while scrolling you have the content flickering through between these elements which is both unattractive and distracting.

As for this, could you please create another issue? It'd be for me to better understand it, and fix it, since I tried what you said, and I definitely see some problems. 

Thank you!

**Comment by alialbaali** [comment]
![IMAGE 2023-06-06 14:40:46](https://github.com/alialbaali/Noto/assets/37933889/1346032b-9529-41e9-a089-b76914916d4a)

Thoughts?

**Comment by uli-on** [comment]
I've not been mailed that last post, I come here by incident. I hope that's been an outlier.

Visibility is sufficient :) Is this meant for only the 2-3 special cases I named or is it intended to generally replace the coloured letters, i.e. for all folder colours?

From the graphic design POV, the padding-bottom on these spans might be reduced a little, so they don't touch each other.

**Comment by alialbaali** [comment]
![IMAGE 2023-06-08 19:28:14](https://github.com/alialbaali/Noto/assets/37933889/a4226da6-8340-4141-8891-3c10a43af64a)

So, I was able to modify the padding, and the background. I made the corners a bit rounded too. However, a slight issue arose which is, the cursor is almost invisible next to the highlighted text.

**Comment by uli-on** [comment]
> the cursor is almost invisible next to the highlighted text.

But the cursor is flashing, at least here? Would have to test, probably. Mostly for seeing how the coloured span reacts if you put the cursor right into the span.

One idea: Does the framework enforce using the same colour for cursor *and* background? If not, you could set the background to - say - 60-70% intensity, which should be visible enough *and* set the cursor a little apart, colour-wise

**Comment by alialbaali** [comment]
Since I was able to modify the background, I can adjust the opacity to be less. However, I will keep it as is for the next beta.

**Comment by alialbaali** [comment]
I discovered a bug while implementing this, regarding cursors being in two places at the same time (idk how 🥲). So, I decided to highlight the current word differently. 

Examples:
![IMAGE 2023-06-10 22:29:24](https://github.com/alialbaali/Noto/assets/37933889/d04faecf-8780-407f-b24b-1433c37f8b0c)

![IMAGE 2023-06-10 22:29:28](https://github.com/alialbaali/Noto/assets/37933889/6f4196df-8862-4fb7-a86f-54b20094664f)

**Comment by alialbaali** [comment]
While we're at it, what do you think about words count being displayed on each note when searching in a folder?

![IMAGE 2023-06-10 22:55:50](https://github.com/alialbaali/Noto/assets/37933889/e3bbc214-3479-403f-b9e0-8bc49f855c19)

**Comment by uli-on** [comment]
> So, I decided to highlight the current word differently.

Frankly, that's the most visible, most usable version! If it could be done like that for the coloured versions, too, that'd be great!

**Comment by uli-on** [comment]
> words count [...] on each note when searching in a folder

For some use cases this might be helpful. But I'd make its visibility pref dependent cause at first glance it doesn't add to the clarity, the conceivableness of the results page and so might be undesired to some. But after some searches and familiarisation, "why not switch it on?"

**Comment by alialbaali** [comment]
> > words count [...] on each note when searching in a folder
> 
> For some use cases this might be helpful. But I'd make its visibility pref dependent cause at first glance it doesn't add to the clarity, the conceivableness of the results page and so might be undesired to some. But after some searches and familiarisation, "why not switch it on?"

Understandable. I'll remove it for now, until I come up with a better design.

**Comment by alialbaali** [comment]
> > So, I decided to highlight the current word differently.
> 
> Frankly, that's the most visible, most usable version! If it could be done like that for the coloured versions, too, that'd be great!

Wonderful! I'll update the colored versions as you suggested :)

**Comment by alialbaali** [comment]
2.3.0-Beta2 has been released, any thoughts?

**Comment by uli-on** [comment]
Thanks for the reminder, will have an opportunity at the weekend.

**Comment by uli-on** [comment]
The search is great now!! I've always hoped to have this kind of continued search in a notes app, from the notes list (and even better like now in Noto: from one level above, i.e. starting from the "General" folder) and have the results displayed not only in the notes list, but inside the single note, be able to jump from result to result, go back to the notes list, all my results still there, open the next note, and so on. And all that combined with the label filtering and hierarchical folders is a-w-e-s-o-m-e for putting and retrieving(!!) all kinds of  miscellaneous stuff with ease!!

**Comment by alialbaali** [comment]
Really glad you like it!
