### ISSUE TITLE
Option to scroll to the searched text

### ISSUE THREAD

**Issue by alialbaali** [alialbaali/Noto#85]
When searching for a text in a folder, and selecting a specific note which contain that text. Noto could scroll to it. This is probably shouldn't be a default behavior, but an option in main settings.

**Comment by uli-on** [comment]
Do you mean really loooong notes, and the app scrolls down to the first instance of a search term? Then I'd say useful, would even be my default.

**Comment by alialbaali** [comment]
Any thoughts after 2.3.0-Beta1?

**Comment by alialbaali** [comment]
You're very welcome!
