### ISSUE TITLE
[Proposal] Add the modification date as sorting criterion ...

### ISSUE THREAD

**Issue by uli-on** [alialbaali/Noto#94]
... and display it inside notes and/or in notes' lists.

**Comment by alialbaali** [comment]
If by modification date, you mean "Accessed at" date, then it's currently showing inside notes. 

However, it's not currently available in the notes' lists nor grouping or sorting by it. I'll add this feature to 2.2.0 roadmap.

**Comment by uli-on** [comment]
I didn't mention the virtual folder that's also possible with the modification date.



> I'll add this feature to 2.2.0 roadmap.

Thank you!

**Comment by uli-on** [comment]
Re-reading this, it looks like we misunderstood each other here. What I actually meant is *that* modification date & time that is set by opening ***and editing*** a note (maybe actually after closing it). 

This modification date might then be used on each of these places where the creation date is currently displayed, additionally or in lieu of the creation date. 

The modification time might also be used for creating a virtual folder, similar to the Recent Notes, for quicker finding recently *edited* ones.

**Comment by alialbaali** [comment]
Adding a modification date along with the access date might be too much, don't you think so? Due to that, I'd prefer fully replacing access date with modification or edition date. 

What do you think?

**Comment by uli-on** [comment]
Yup, that'd be too much. 
And there are more places of utilization I forgot mentioning, "sort by" and "group by".
