### ISSUE TITLE
Sort labels by position after being sorted with selection

### ISSUE THREAD

**Issue by alialbaali** [alialbaali/Noto#95]

**Comment by uli-on** [comment]
Sorry for the duplicate, but I didn't understand this issue here in all its terseness, and I still don't get what to do to avoid it. Also: Can I repair my database myself by any 'legal' action?

**Comment by alialbaali** [comment]
It's okay. I guess the title isn't as understandable, maybe I should change it. 

There's nothing you can do to avoid it, it's not some settings as it's a hard coded value, and has been fixed already, see [0d631a2](https://github.com/alialbaali/Noto/commit/0d631a238fec507ad3f1eda310a6c90e3a1a9eae).

The fix is going to be released in 2.2.0. If you really need the fix now, I could build a new APK which contains the fix, what do you think?

**Comment by alialbaali** [comment]
Version 2.1.5 is published. Check it and let me know!
