### ISSUE TITLE
The Arabic text is cut off in the notes list

### ISSUE THREAD

**Issue by AI-IMED** [alialbaali/Noto#99]
The problem of the Arabic text being cut off, caused by italic font, has been resolved in the note screen, but the problem has not been resolved in the notes list.

![Screenshot_٢٠٢٢٠٨٠٣_١١٣١٠٤](https://user-images.githubusercontent.com/38974362/182632613-4bfacd0e-2b0f-4c49-8717-df8d2edb1d51.jpg)

* I would like to remind you again: Since the application displays the correct interface language based on the system language when installing, so it is better that these corrections are also based, and the correction that is related to stopping the animation of the Arabic text in counter (notes and folders) is based on the system language (when it is  Arabic), because new Arab users will undoubtedly face the problem, because they do not know that they have to manually choose the Arabic language from within the application.

**Comment by alialbaali** [comment]
What other places do you face this? So I can try to fix all of them. I have fixed it in notes list, note's dialog options, and in widgets preview. 

One place left is widgets themselves, and widgets are hard to style them. Meaning, if I have to disable italics for Arabic, then I would have to disable it for all languages too.

**Comment by afmbsr** [comment]
Yes, these are the same places, but I just wanted to make sure, if you mean that the fix includes a list of notes anywhere, if so, that is what is needed, because there is a list of notes of type (Grid) , a list in the archive, a list in "  Recent Notes", and a list in "All Notes".

**Comment by alialbaali** [comment]
The fix is applied everywhere, except widgets.

**Comment by afmbsr** [comment]
Well, that's okay

**Comment by alialbaali** [comment]
The fix isn't out yet. Why did you close it?

**Comment by afmbsr** [comment]
I'm sorry,☺️

**Comment by alialbaali** [comment]
It's okay. :)

**Comment by AI-IMED** [comment]
Fixed it in v2.2.0 Beta1,Thanks
